### ISSUE TITLE
IExecutionSegment.Labels is deprecated and there is no replacement to get a label value

### ISSUE THREAD

**Issue by tbutler-qontigo** [elastic/apm-agent-dotnet#1033]
**Describe the bug**
In 1.7.0 the Labels dictionary has been marked as deprecated with a message to use SetLabel instead.
This is fine for setting but what about getting the label value?
We run with <WarningsAsErrors /> so this fails our builds

**To Reproduce**
1. Use version 1.7.0
2. Set Warnings as Errors in your csproj file
2. Then create a transaction: var transaction = Agent.Tracer.StartTransaction(...)
3. Then access transaction.Labels - transaction.Labels["someLabel"] or transaction.Labels.ContainsKey("someKey") 
4. See the error when you build

**Expected behavior**
I would expect replacements to be available to a) get a label and b) assert if a label exists.

**Comment by gregkalapos** [comment]
Thanks for opening this @tbutler-qontigo  - this is useful feedback.

The `Labels` dictionary which is marked as obsolete should work as it did before in `1.7.0`, but we plan to remove it at some point in the future. Reason for this is that it only supports strings, but we want to offer an API to also support `bool` and numbers. Only thing to keep in mind is that if you set something with the new `SetLabel()` method, you will not get the value back from the `.Labels` dictionary even if it's a string.

> We run with so this fails our builds

These obsolete usages should by-default produce a warning. In this case as of now it's safe to ignore those warnings in your tool. E.g. you can do [this](https://stackoverflow.com/a/968311/1783306) - with that you can still keep treating warnings as errors.

> This is fine for setting but what about getting the label value?

That's actually a use case we thought no one would do. But I'm totally aware that it was possible with the old API (and that's why we kept it as it is for now). Can you share a bit more about your use case? Like, why do you read the value back? What exactly do you do with it? We thought people will just set a label, and expect the value to show up in Elasticsearch, but never really wanting to read it back in C#.

**Comment by tbutler-qontigo** [comment]
Hi @gregkalapos Thanks for getting back to me.
I know I could #pragma my way out of this but using something that is obsolete today is only storing up a problem for tomorrow so we have a strong preference to avoid obsolete methods and properties - after all, the point of marking them as such is to indicate that they will go away at some point so consumers should start using the replacement methods and properties now right?

Our current use case is in fact just in unit tests of some custom middleware which creates labels under certain circumstances but not others - our tests verify this behaviour.
Going forward, we may have occasion to extract labels in actual application code.
For example we pass APM context via remoting to service fabric services.  We may wish to extract a custom correlation id and attach it to all our logs (we use serilog writing to Elasticsearch) as well as having it in our APM labels so we can more easily correlate logs to APM traces and vice versa.

**Comment by gregkalapos** [comment]
@tbutler-qontigo, thanks for the details.

We discussed this and we decided to add a reading method as well, since we really don't want to break our users' code.

I just opened https://github.com/elastic/apm-agent-dotnet/pull/1057, you can see the proposed API there, this is the best point to give feedback on it.

Since we support multiple types I feel it's better to go with methods instead of a property.

For now in `1.7.0` you could keep the old `.Labels` property, and maybe the next release would be a good point for you to move to the new API where we intend to have the `GetLabel` method (assuming https://github.com/elastic/apm-agent-dotnet/pull/1057 makes it into the release).

**Comment by tbutler-qontigo** [comment]
Thanks @gregkalapos - I'll take a look at the PR.
Agreed that using the deprecated properties now and the new functionality in the next release makes sense.
Thanks for the quick response

**Comment by gregkalapos** [comment]
https://github.com/elastic/apm-agent-dotnet/pull/1057 merged.
