### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-dotnet#1121]
## Overview

An official docker image for the APM .NET agent would simplify the use of the agent in a Kubernetes environment. Per @eyalkoren:
> One advantage I think there is for using a Docker container is that it is native to k8s, meaning - you are guaranteed to have an accessible docker registry to pull images from, as opposed to downloading files from external resources that may be restricted in some environments.

For now, we do have a [workaround](https://github.com/elastic/observability-docs/pull/151#issuecomment-754784081) documented.

## Related

The Java agent already publishes an official docker image. Their implementation issue offers a ton of additional information: https://github.com/elastic/apm-agent-java/issues/997

**Comment by eyalkoren** [comment]
To complete the picture, [this](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#docker-images) is a reference to the process we do per each release.
You should talk to @cachedout about baking it into your release process.
Mike, sorry for referring more things over to you, if you don't like this you need to reduce your usefulness 😛

**Comment by cachedout** [comment]
@eyalkoren Hah! I'm actually really happy when we can be of service to teams! Thanks for alerting me to this.

@bmorelli25 We should definitely talk about this. There may be a lot of what we did for the Java folks that we could re-use for you.

**Comment by russcam** [comment]
++ this will be useful for #1073, to test the startup hook

**Comment by felixbarny** [comment]
As there's a good [workaround](https://github.com/elastic/observability-docs/pull/151#issuecomment-754784081) in place (downloading the agent binaries via wget in an init container), I'd say that the priority for this is not critical. Especially, because the longer-term direction is to rely on the agent binaries bundled with APM Server rather than Docker images containing the agent binaries for k8s. See also https://github.com/elastic/apm/issues/383

But if we get to it, it would be nice to completely automate the step of publishing the Docker image. We manually publish Docker images for the Java agent for quite a while now which makes the release process more painful. So if we want to extend the Docker image publishing to other agents such as .NET and Node.js, I think automating that step during the release is a requirement.

**Comment by russcam** [comment]
This has been implemented

https://github.com/elastic/apm-agent-dotnet/blob/bab776194d91a8e65be077d3ad1f5db3f38f81b4/build/scripts/Build.fs#L241-L250

which can be built with
```
./build.[sh|bat] agent-docker
```
_(use .bat on Windows and .sh on non-Windows)_

so a docker image with startup hooks can be built, but we don't artifact it. I'm going to close this issue out for now, and if an ask comes up for publishing the image, we can handle it in a new issue.
