### ISSUE TITLE
[META 382] Zero-configuration support

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1131]
Implement zero-configuration support for the agent as described in: https://github.com/elastic/apm/issues/382

SPEC issue: https://github.com/elastic/apm/issues/401

**Comment by gregkalapos** [comment]
I looked into this, we are good here, the .NET Agent fulfils the requirements.

Specifically:


> Agents should be able to auto-detect the APM Server endpoint by just defaulting to localhost:8200. 

That's true in the .NET agent.


> Furthermore, agents should detect a sensible default `service.name` as well as the `service.version`, if possible.

For both of these, if those are not configured, the agent will read the entry assembly and report that (`service.name` will be the name of the entry assembly (e.g. `myapp` in case of `myapp.exe`) and `service.version` will be the `AssemblyInformationalVersionAttribute` of this assembly - this is in my opinion natural for .NET apps). There are some cases when reading the entry assembly is not possible, this is when the CLR is hosted manually in a native process - one common example of this is IIS, we handle that by reading the app pool name and reporting that as `service.name` - I think in this case we don't set `service.version`. If it's a hosted CLR and a non-IIS process (super super edge case) then we report `service.name = unknown`.

I move this issue back to milestone `7.12` since all I write here was true in the `7.12` time-frame (in fact since the beginning of the agent).
