### ISSUE TITLE
[META 410] Instrumentation for Azure ServiceBus

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1157]
Provide instrumentation for Azure ServiceBus.

Meta issue: elastic/apm#410
SPEC: elastic/apm#411

**Comment by glucaci** [comment]
Hi,
Is someone working on this? If not I will start to create something because we also need it.

We have already created support for MassTrasit which is supporting [multiple transports](https://masstransit-project.com/usage/transports/) frameworks. 
https://github.com/swisslife-oss/elastic-apm-extensions#masstrasit

Let me know if you want to integrate it in Elastic Agent and I will do a PR.

**Comment by gregkalapos** [comment]
@glucaci I think no one actively works on this right now.

The plan was to directly support [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus). I haven't looked much into it, but from what I saw this could be covered by diagnostic source. If you want to open a PR, I'm happy to review it.

Regarding MassTrasit: It wasn't on our roadmap so far, I can sync up on it internally.

**Comment by russcam** [comment]
I'll take a look at this
