### ISSUE TITLE
Stacktrace Namespace Exclusion does not work

### ISSUE THREAD

**Issue by fuzolan** [elastic/apm-agent-dotnet#1183]
I'm using the Client 1.7.1 and it does not matter if I use the Setting ElasticApm:ExcludedNamespaces or ElasticApm:ApplicationNamespaces. My Stacktraces always have Entries from Microsoft, System and so on. No filtering is applied here.

**Comment by gregkalapos** [comment]
The `ExcludedNamespaces` and `ApplicationNamespaces` settings are used to determine the culprit of an exception. I just looked at the code and it seems to do exactly what the [docs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-stacktrace.html#config-excluded-namespaces) say - e.g. `ExcludedNamespaces`:
> A list of namespaces to exclude when reading an exception’s StackTrace to determine the culprit.

Reading the issue description makes me thing you expect some trimming here - like frames with a given namespace won't be in the stack trace. But that's not the case, these settings are not used for that. The [`StacktraceLimit`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-stacktrace.html#config-stack-trace-limit) config does something similar, but it does not work based on namespaces.

**Comment by gregkalapos** [comment]
Closing now - feel free to reopen if you need a follow-up.

**Comment by fuzolan** [comment]
@gregkalapos so, it's only useful to exclude a complete stacktrace from a specific namespace, but then the complete stracktrace is there? It would be nice to filter stacktrace items with that. The stacktraces consumes a lot of space. For me only the hits in my namespace would be relevant. Is there a difference between collecting stracktraces for exceptions and stacktraces for spans?

**Comment by gregkalapos** [comment]
>  so, it's only useful to exclude a complete stacktrace from a specific namespace, but then the complete stracktrace is there? 

No, it's useful to determine the culprit. For example, let's say you have this callstack:

```
System.String.ToString()
SomeLibIUse.SomeMethod()
MyBusinessLogic.MyMethod()
```

For determining the culprit the agent knows that `System.` won't help you since it's a system namespace, so it'll jump to the next frame, which is `SomeLibIUse` - that's not a system namespace, so it'll use that for culprit. But let's say it does not help you either, because it's just a library, which you use everywhere in your code. In this case you can add `SomeLibIUse` to `ExcludedNamespaces` and with that the agent will treat it as a non-application frame and when the culprit is determined it'll be also skipped resulting `MyBusinessLogic.MyMethod` as the culprit.

> It would be nice to filter stacktrace items with that. The stacktraces consumes a lot of space. For me only the hits in my namespace would be relevant.

I see - yeah, I understand the problem. I can't really offer an out-of-the-box solution, but have you looked at the [Filter API](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#filter-api) of the agent? You could just register a filter for spans and errors, and remove specific frames manually. It's a little bit of a work, but with that you can achieve what you aim for.

Here is a small example to get you started - of course you can do way more here:

```
Agent.AddFilter((ISpan span) =>
{
	span.StackTrace.RemoveAll(n => n.Module.Contains("MyNamespace"));
	return span;
});
```

If you don't want to do it in C#, the other option you have is to define an [ingest node](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html) on the elasticsearch level.

I hope one of those two options will help you.

> Is there a difference between collecting stracktraces for exceptions and stacktraces for spans?

I'm not sure what you'd like to get to with the question - so I'm not sure my answer helps. The answer is yes, for spans the agent actively triggers a stack trace collection, for exceptions it just reads it from the `Exception` object. Also there are some settings that only apply to spans (e.g. [`SpanFramesMinDuration`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-stacktrace.html#config-span-frames-min-duration)), but some others apply to both.
