### ISSUE TITLE
Fix max length for span name

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#119]
Max length for span name is 1024 (apm server configuration). 

In the case of entity, db queries span name = query content, and query length can be greater than 1024 characters.  http://joxi.net/5mdJeEHkbP4eA1

We need to limit max length for span name, a transaction cannot be recorded on APM server

**Comment by gregkalapos** [comment]
Thanks for reporting this! 

We have this problem for multiple strings - currently we don't truncate anything. Probably the span name is the most important one, since as you point out, that can cause invalid requests to the APM server.

The PR already fixes it, and I think it's fine to fix just `Span.Name` now and take a look at the other fields later.
