### ISSUE TITLE
Agent send metrics when no configuration in appsettings

### ISSUE THREAD

**Issue by chtourou-youssef** [elastic/apm-agent-dotnet#1209]
### APM Agent version
7.10.1

### Environment

OS : Linux
 
Net Framework  : 2.2

### Describe the bug
The agent  send always to APM (localhost) , when no server configuration

this the error : 
`2021-02-25 14:54:16.392 +00:00 [Warning] {"PayloadSenderV2"} Failed sending events. Following events were not transferred successfully to the server ("http://localhost:8200/"):`

**Comment by gregkalapos** [comment]
Hi @chtourou-youssef,

this is by design. If you don't configure any `serverurls`, the agent will try to send data to an APM server on `localhost`.

If you'd like to completely disable the agent, we have a specific [setting](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-core.html#config-enabled) for that.
