### ISSUE TITLE
Don't overwrite the transaction outcome if it is already set.

### ISSUE THREAD

**Issue by merula** [elastic/apm-agent-dotnet#1349]
**APM Agent version**
1.11.0

**Is your feature request related to a problem? Please describe.**
We have a solution where we return a 404 if someone asks for a key that doesn't exists, as this is a public API we don't want to count those 404:s as errors, as it hides the really problems that we send as 500 errors.

**Describe alternatives you've considered**
Tried to set the Outcome of the transaction before returning the 404 but it gets overwritten when the result is processed.

**Describe the solution you'd like**
If a transaction.Outcome is set then do not overwrite it in the processing of the result

**Additional context**
Asp.net core 5 app and uses app.UseAllElasticApm() to enable Elastic APM

**Comment by russcam** [comment]
Hi @merula,

The agent sets a flag when the Outcome is explicitly changed on a transaction, then uses this when the transaction ends to determine whether to change an unknown outcome that hasn't been explicitly set to a successful outcome:

https://github.com/elastic/apm-agent-dotnet/blob/07a448406c78871a59088f87edaf3bcc191c2e67/src/Elastic.Apm/Model/Transaction.cs#L474-L476 

Based on this, I wouldn't expect an explicitly set outcome to be changed. Are you able to provide more explicit detail on the steps being taken and the values assigned?

**Comment by gregkalapos** [comment]
I think @merula has a point here.

The code @russcam linked is intended to avoid overwriting `Outcome` when set via public API. Unfortunately that did not work, because caller code (specifically [`WebRequestTransactionCreator.SetOutcomeForHttpResult`](https://github.com/elastic/apm-agent-dotnet/blob/d924d8dee4e203055cc27447d249ae96f7d03b5d/src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs#L240-L245)) called the public `Transaction.Outcome` property to set the outcome right before the agent ended the transaction - and with that the check did not work. I opened https://github.com/elastic/apm-agent-dotnet/pull/1472 to fix this.

**Comment by gregkalapos** [comment]
Fixed in https://github.com/elastic/apm-agent-dotnet/pull/1472.
