### ISSUE TITLE
[BUG] Time spend by Span - Counting database twice

### ISSUE THREAD

**Issue by andrewharry** [elastic/apm-agent-dotnet#1477]
### APM Agent version
Elastic.Apm 1.11.0

**Operating system and version:**
Windows 10 64bit
.NET 5

### Describe the bug
![image](https://user-images.githubusercontent.com/1200776/131287065-2ccadfd1-a60f-4d35-8239-eafe0cb707bd.png)

The time spent by span type is double counting my database spans (db and oracle).
I am marking my custom EF Core spans with Type: DB and SubType:Oracle
Which makes this even more confusing.... why are the two values different? (not straight double counting)
I am not using a different database.  every db span is marked the same

Is this expected behavior? 

Should I remove the Subtype from my spans?

![image](https://user-images.githubusercontent.com/1200776/131287444-1486909b-238a-434d-ae54-9306a7a92894.png)

**Comment by gregkalapos** [comment]
By sending 2 different spans - both manually created with type: `db` and subtype `Oracle` I'm unable to reproduce this. I have two guesses which can cause this:

1) Do you maybe have auto instrumentation also capturing the db calls? You mentioned you "marking my custom EF Core spans...", so I assume you use the public API to capture the spans. We also have EF Core auto instrumentation which is turned on by default. If that's the case on the transaction flow you'd also see 2 spans. [Here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-asp-net-core.html#setup-asp-net-core) some docs on how you can control auto instrumentation.

2) You simply have some spans where the subtype is not set. I think this is more likely, because in the 1. case with auto instrumentation the agent would take the name of the db type as subtype and not just `db` 

To show this in action, here is a small sample I created (I just loop through this code). 2 spans, both with `type: db`, `subtype: oracle`.

```
var transaction = Agent.Tracer.StartTransaction("SampleTransactionWithSpan", ApiConstants.TypeRequest);
Thread.Sleep(500);
var span = transaction.StartSpan("SampleSpan", ApiConstants.TypeDb, "Oracle");
Thread.Sleep(200);
span.End();
var span2 = transaction.StartSpan("SampleSpan2", ApiConstants.TypeDb, "Oracle");
Thread.Sleep(100);
span2.End();
transaction.End();
```

And here is how the chart looks:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1091853/132533018-b602ca1c-bfa0-469d-a255-a6ed6bd511d4.png">


Once I change the code to not send `subtype: Oracle`: (same code as above, except one span is just `type: db` with empty subtype:
 ```
var transaction = Agent.Tracer.StartTransaction("SampleTransactionWithSpan", ApiConstants.TypeRequest);
Thread.Sleep(500);
var span = transaction.StartSpan("SampleSpan", ApiConstants.TypeDb);
Thread.Sleep(200);
span.End();
var span2 = transaction.StartSpan("SampleSpan2", ApiConstants.TypeDb, "Oracle");
Thread.Sleep(100);
span2.End();
transaction.End();
```

The chart looks like this:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1091853/132535201-b2c46b02-e390-4fbb-93fc-6e507e614771.png">


Could you maybe double check you code to see if any of my guesses is correct? If not we'll need to look further.

**Comment by gregkalapos** [comment]
Closing now for inactivity. To me this looks ok and no bug found after investigation.


Feel free to reopen if needed.
