### ISSUE TITLE
Move to Stopwatch.GetTimestamp for measuring duration

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1654]
From https://discuss.elastic.co/t/incorrect-span-duration/299442

Currently we use `DateTime.Now`, moving to `Stopwatch.GetTimestamp` would give us higher precision. 

Steps:
- [x] Decide if we want to make this change
- [ ] If yes, implement it

**Comment by z1c0** [comment]
I could reproduce the behavior on a **Windows 11** machine with **.NET Framework 4.8**.

In this constellation, the infamous "Windows 16 ms resolution inaccuracy" becomes evident immediately as the screenshot below shows.

> *Note:* The code sample I used to reproduce the issue creates spans of the following durations:
> * 20 ms
> * 10 ms
> * 5 ms
> * 1 ms
> * 1 tick

<img width="838" alt="spans_dotnet48_default" src="https://user-images.githubusercontent.com/4700296/186367553-bab9d283-d5b2-4319-9ca7-c6457a2f42ea.png">

Running the same sample application with **NET 5** (also on Windows) works, however.

<img width="851" alt="spans_dotnet50_default" src="https://user-images.githubusercontent.com/4700296/186367557-3e908c9f-a3c4-4888-a36c-f884782629bb.png">

A quick prototype using a high-resolution timer (as suggested [here](https://manski.net/2014/07/high-resolution-clock-in-csharp/ ) or [here](https://www.anycodings.com/1questions/51916/how-to-get-timestamp-of-tick-precision-in-net-c)) also gives the desired exact timings on **Windows 11 / .NET Framework 4.8**.

<img width="845" alt="spans_dotnet48_hires" src="https://user-images.githubusercontent.com/4700296/186367556-de8f2400-99c6-452b-b21d-9d9a04426751.png">

## Suggested next steps

Update the implementation of `TimeUtils.TimestampNow` so that it uses a custom high-resolution timer **only** on .NET full framework.

**Comment by z1c0** [comment]
To my surprise, the basic unit test in my [draft PR](https://github.com/elastic/apm-agent-dotnet/pull/1808) did not reproduce the problem. After further research, it turned out that the behavior is even different among .NET 4 Framework version on Windows.

* `net461`: This is the version used for the unit test project `Elastic.Apm.Tests`. It uses `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\mscorlib.dll` and gives `DateTime.UtcNow` with the expected precision.
* `net480`: This is the version is used for my initial tests with a sample app. It uses`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\mscorlib.dll` where `DateTime.UtcNow` does **not provide the required precisions`.

Interestingly, the decompiled code for `DateTime.Utc` looks the same in both versions:

```c#
//
// Summary:
//     Gets a System.DateTime object that is set to the current date and time on this
//     computer, expressed as the Coordinated Universal Time (UTC).
//
// Returns:
//     An object whose value is the current UTC date and time.
[__DynamicallyInvokable]
public static DateTime UtcNow
{
    [SecuritySafeCritical]
    [__DynamicallyInvokable]
    get
    {
        long num = 0L;
        if (s_isLeapSecondsSupportedSystem)
        {
            FullSystemTime time = default(FullSystemTime);
            GetSystemTimeWithLeapSecondsHandling(ref time);
            return CreateDateTimeFromSystemTime(ref time);
        }

        num = GetSystemTimeAsFileTime();
        return new DateTime((ulong)(num + 504911232000000000L) | 0x4000000000000000uL);
    }
}
```
Apparently, the native calls are implemented differently in `mscorlib`.

Using a custom high-resolution clock for .NET 4 frameworks (Windows-only) would still work thought. However, let's discuss this again shortly after your PTO @gregkalapos.

**Comment by z1c0** [comment]
After some research, I have reached the conclusion that in order to fix this problem, we should take the monotonic clock approach (https://github.com/elastic/apm-agent-dotnet/issues/139) after all.

The original idea was to fix the observed problem for Windows/.NET Framework 4.8 specifically and follow up with the general switch to a monotonic clock implementation at a later stage.

However, after trying several approaches, I could not come up with a reliable isolated solution that would solve this problem in .NET Framework 4.8.

The main problem with this isolated fix is that it always requires a combination of a:
* `DateTime.Utc` timestamp
* High-precision offset in ticks.
 
The viable candidate for such an offset would be `StopWatch.Elapsed.Ticks`. However, this has the significant downside of a noticeable **clock drift** that occurs after a relatively short amount of time (up to a second within an hour).
For that reason, the `StopWatch` needs to get "synchronized" (i.e. a new instance created) regularly with the wall clock time, which introduces two problems:

* Additional GC pressure due to repeated instance creation.
* More significantly, this can **time jumps** (even in a negative direction).

**Comment by aputlock** [comment]
As an alternative approach, would it be a big lift to update the code paths to accept a TimeProvider (via net8 or [bcl nuget package](https://www.nuget.org/packages/Microsoft.Bcl.TimeProvider/)) to provide indirection to grabbing the timestamp? This would allow netfx users to supply an alternative implementation that hits the [precise](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) windows time api (which backs the netcore+ `DateTime.UtcNow` api https://github.com/dotnet/coreclr/pull/9736)

**Comment by aputlock** [comment]
@stevejgordon Any thoughts on the above approach? (sorry for the @, just wanted to make sure someone saw this given the thread necromancy -- happy to also open a new thread if that's better)
