### ISSUE TITLE
[BUG] Not able to get Elastic Trace for .net Console App

### ISSUE THREAD

**Issue by sachinagarwal010** [elastic/apm-agent-dotnet#1700]
### APM Agent version
The version of the `Elastic.Apm` nuget package used 1.15.0

### Environment

**Operating system and version:** Windows 10

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) : .net Core 3.1

### Describe the bug
When we are trying to integrate Elastic with .net Console App then only after injecting the UseAllElasticApm middleware we are not getting traces. its coming only if we add the below line of code.

`await _apmAgent.Tracer.CaptureTransaction("Console .Net Core Example", "background", async () =>`

### To Reproduce

Attached sample for same. 

#### Expected behavior
Tracing should come without adding capture transaction method.

#### Actual behavior

[SampleConsoleNetCoreApp.zip](https://github.com/elastic/apm-agent-dotnet/files/8684006/SampleConsoleNetCoreApp.zip)

**Comment by gregkalapos** [comment]
This is currently the expected behaviour.

In the console app you have a background service and within the background service you execute outgoing HTTP calls.

Outgoing HTTP calls don't start a transaction - those are spans. And spans are only captured when there is an active transaction. In the background service we don't automatically start a transaction, therefore you have to do it manually.

If each outgoing HTTP transaction would start its own transaction then you'd have lots of transactions for each outgoing HTTP call which would be very confusing.

So at this point you won't be able to get rid of the `_apmAgent.Tracer.CaptureTransaction`. We are looking into way to maybe have something where it's not needed in the future.
