### ISSUE TITLE
[BUG] Redis instrumentation error in 1.16.0

### ISSUE THREAD

**Issue by NicolasREY69330** [elastic/apm-agent-dotnet#1730]
### APM Agent version
v1.16.0

### Environment
Docker on Windows 10/WSL2

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :
.Net v6.0

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):
net6.0

### Describe the bug
On any instrumentation involving Redis an error is logged in v1.16.0 and nothing is reported to APM.
It works as expected on v1.15.0

```
[12:21:54 ERR] {ElasticApmProfiler} Exception ending profiling session for transaction 0094d69c014e0e72
System.MissingMethodException: Method not found: 'Void Elastic.Apm.Api.IExecutionSegment.CaptureSpan(System.String, System.String, System.Action`1<Elastic.Apm.Api.ISpan>, System.String, System.String, Boolean)'.
   at Elastic.Apm.StackExchange.Redis.ElasticApmProfiler.ProcessCommand(IProfiledCommand profiledCommand, IExecutionSegment executionSegment)
   at Elastic.Apm.StackExchange.Redis.ElasticApmProfiler.EndProfilingSession(Object sender, ProfilingSession session)   
```
Seems to reference https://github.com/elastic/apm-agent-dotnet/blob/20fea7888fd3a044e13fb34c3e657d26502a6911/src/Elastic.Apm.StackExchange.Redis/ElasticApmProfiler.cs#L143-L148

### To Reproduce
```csharp
                        await Agent.Tracer
                            .CaptureTransaction("TestTransaction", "test", async (t) =>
                            {
                               var myvalue = await _cacheClient.Get<MyClass>("AnyKey"); 
                               _logger.LogInformation(myvalue);
                            });
```
with redis client
```csharp
public class CacheClient : ICacheClient
    {
        private readonly Lazy<IConnectionMultiplexer> _connection;
        private readonly Configuration _configuration;
        private readonly ILogger<CacheClient> _logger;

        public CacheClient(Configuration configuration, ILogger<CacheClient> logger)
        {
            _connection = new Lazy<IConnectionMultiplexer>(() =>
            {
                ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(configuration.ConnectionString);
                return redis;
            });

            Connection.UseElasticApm(); // Set APM instrumentation here
            _configuration = configuration;
            _logger = logger;
        }

        public IConnectionMultiplexer Connection => _connection.Value;
        public IDatabase Database => Connection.GetDatabase();
        public IServer Server => Connection.GetServer(_configuration.ConnectionString);

        public T Get<T>(RedisKey key, CommandFlags flags = CommandFlags.None, SerializerType serializerType = SerializerType.TextJson)
        {
            try
            {
                RedisValue rv = Database.StringGet(key, flags);
                if (!rv.HasValue)
                    return default;
                return rv.ToString().Deserialize<T>(serializerType);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Can't get {key} from Redis", key);
                return default;
            }
        }
}
```

#### Expected behavior
No error and instrumentation reported to APM

**Comment by gregkalapos** [comment]
@NicolasREY69330 I think this is a version mismatch.

[`Elastic.Apm.StackExchange.Redis`](https://www.nuget.org/packages/Elastic.Apm.StackExchange.Redis#dependencies-body-tab) v1.16.0 depends on [`Elastic.Apm`](https://www.nuget.org/packages/Elastic.Apm/) v1.16.0.

In v1.16.0 the signature of the method `Elastic.Apm.Api.IExecutionSegment.CaptureSpan` changed. Based on the method signature of the exception you pasted it seems it tries to call the method with the old signature.

This makes me think that `Elastic.Apm.StackExchange.Redis` v1.15.0 (or definitely a version older than v1.16.0) is loaded, while `Elastic.Apm` is already on v1.16.0 (that's why it doesn't find the method with the old signature). Maybe I'm wrong about the specific versions, but it definitely seems like a version mismatch. 

We have tests covering this, and this issue does not happen locally and in our CI.

Could you please check which versions of the specific 2 assemblies (`Elastic.Apm.StackExchange.Redis` and `Elastic.Apm`) are loaded?

**Comment by NicolasREY69330** [comment]
Hi @gregkalapos and thank you for your useful reply, you're right, here was my packages
`"Elastic.Apm.NetCoreAll" Version="1.15.0"` <== here was the problem
`"Elastic.Apm.StackExchange.Redis" Version="1.16.0"`

I updated all *APM* packages to 1.16.0 and the problem is solved, thank you
