### ISSUE TITLE
[META 352] AWS Lambda support

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1764]
## Meta issue
- https://github.com/elastic/apm/issues/352

## Description
[Follow the description on the AWS lambda agent spec](https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-aws-lambda.md).

## Related
- #518
- #288

**Comment by Chompetto** [comment]
Just checking to see if this ticket is on the radar for any future updates.  
It is just odd to see support for Node, Python & Java while the .NET one does not support Lambdas at all. (Unless there is a workaround I am not seeing)

Thanks!

**Comment by gregkalapos** [comment]
Hi @Chompetto 

yes, it's definitely on our radar. We are aware that the .NET Agent is behind the other agents in terms of lambda support, and we definitely want to catch up.

There is no ETA at this point, but you can watch progress on this issue.

**Comment by jonatanzazula** [comment]
It's been over a year since the last reply in this thread. Are there any plans to add this support? 

Also, is there any workaround for enabling lambda support? The minimum I need is to redirect the logs to the apm server.

**Comment by Chompetto** [comment]
@jonatanzazula 
I had a small middleware workaround that forced the elastic queue to be processed at the end of every request.  Required some reflection I believe since the queue was internal, which wasn't optimal. This was a year ago.
Just tossing my workaround out there in the chance or helps at all.

**Comment by jonatanzazula** [comment]
@gregkalapos Do you perhaps know if there are any intentions to implement and when this agent will be available?

**Comment by gregkalapos** [comment]
We discussed this internally and our conclusion on AWS lambda support is the following:
- Since this issue got created we prioritized OTel support, specifically the OTel APM Agent over this APM Agent
- Implementing (and properly testing) AWS Lambda for this agent would be significant work
- Therefore we suggest OTel for AWS Lambda in .NET
- If the support for AWS Lambda in the OTel .NET SDK/Agent is not good enough we'd be happy to look into improving that later.

Closing this issue with this.
