### ISSUE TITLE
application/json request body is not captured when CaptureBody set to errors and HTTP response status >= 400

### ISSUE THREAD

**Issue by MarkitoAgnito** [elastic/apm-agent-dotnet#1807]
Elastic.Apm.AspNetCore 1.17.0
Windows 10 Pro 
netcoreapp3.1:

#### Description
When posting application/x-www-form-urlencoded the request body is captured as expected. However performing any operations using application/json the body is set to N/A

#### To Reproduce
Use this config 'CaptureBody: errors'
Then send a request using application/json which returns a status code >= 400
Check elastic APM and http.request.body.original == N/A

#### Expected behavior
http.request.body.original should contain the body

#### Actual behavior
http.request.body.original == N/A

###Other
If I use the exact same setup but post a request using application/x-www-form-urlencoded, the body is captured as expected.

**Comment by MarkitoAgnito** [comment]
So is this only expected to work with application/x-www-form-urlencoded?

**Comment by z1c0** [comment]
Hi @MarkitoAgnito,

can you check your settings for [CaptureBodyContentTypes](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-http.html#config-capture-body-content-types), please?
Is `application/json` included there?
Also, does it work for you in non-error (e.g. status code 200) cases?

**Comment by z1c0** [comment]
Hi @MarkitoAgnito,

would it be possible to reproduce the issue, capture the agent log with a [log level](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-supportability.html#config-log-level) set to `Trace` and attach this log to issue?

**Comment by z1c0** [comment]
Hi @MarkitoAgnito,

did you get a chance to look into my last [https://github.com/elastic/apm-agent-dotnet/issues/1807#issuecomment-1251177380](comment)?

Unfortunately, I was not able to reproduce the reported problem on our end.
The simplest test I could think of was just `POST`ing `JSON` data to a non-existing route (resulting in a `404` error response).
This however resulted in the expected behavior and the `JSON` data shows up on the transaction (with `"CaptureBody": "errors"` enabled).

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/4700296/195853688-493484be-5544-4c1f-8233-b9064f030544.png">

Could you give this simple scenario a try and let me know whether it works for you or not?
If you have another test case for me to try out and reproduce the problem, I'll be happy to help.

**Comment by MarkitoAgnito** [comment]
Hi Wolfgang,
Ill try stripping everything back when i havecan opportunity to see if this
helps show where im getting the issue.

Thanks
