### ISSUE TITLE
Add support for global labels

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-dotnet#183]
See https://github.com/elastic/apm/issues/48

**Comment by ThomasMaij** [comment]
Hi Guys, is there any estimate when this will be implemented. We would love to start using your .net apm client but because tags/labels are missing this is a big issue for us at the moment. We use Logstash to filter on the log to send it to the correct index in ElasticSearch.

**Comment by axw** [comment]
@ThomasMaij no estimate at this time sorry. We're busy stabilising the core functionality for an upcoming beta release. Global labels are a new thing (not supported by any released APM Server), so they haven't been a high priority for the .NET agent so far.

Can you please provide a bit more info on what kind of labels you'd apply, and why you need them for routing?

**Comment by ThomasMaij** [comment]
@axw I was away for a few days. But to answer your question:

Here the flow is APM Agent -> APM server -> Logstash -> Kibana index
And logstash now filters on APM server hostname to send apm logs to the correct index.
Because the people that manage these services don't like to filter on the hostname, they want me to provide them some tags/labels with the APM data. 

We found out that we could write a custom middle ware (.net Core) to add those tags/labels for all requests. I could also add for example correlation Id's in the same way.
I think this might be sufficient for the the time being.

**Comment by SergeyKleyman** [comment]
https://discuss.elastic.co/t/are-env-labels-supported-in-elastic-apm-agent/187556/2
