### ISSUE TITLE
[BUG] Error logs to APM Errors depends on the UseAllElasticApm() location

### ISSUE THREAD

**Issue by NicolasREY69330** [elastic/apm-agent-dotnet#1901]
### PM Agent version
The version of the `Elastic.Apm` nuget package used
`<PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.18.0" />`
### Environment
Docker / WSL2
**Operating system and version:**
Windows 10 Pro
**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :
.net 6
**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):
net6
### Describe the bug
Hi, we just noticed that by logging an error, the APM agent is supposed to create an error transaction just like it's described in the following topics
https://discuss.elastic.co/t/how-to-record-level-error-logs-to-apm-errors/275601/2?u=nicolas_rey
https://discuss.elastic.co/t/error-does-not-display-in-apm-errors/274779/5?u=nicolas_rey
https://github.com/elastic/apm-agent-dotnet/pull/1135

In our project it doesn't work (the error only appears in APM if the code throws in a running transaction or if we manually capture the exception or error using the APM client public API).

By cloning the @gregkalapos small sample (https://github.com/gregkalapos/LogAsErrorMiniSample) I made it work. And I finally found what differs from our project and from this sample, this is the `UseAllElasticApm` location.

### To Reproduce

1) To make it works (an error is  reported in APM when `_logger.LogError()` is called)
Place the `UseAllElasticApm` in Program.cs as the sample does 
```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); })
		.UseAllElasticApm(); // here
```

2) To make it fails (no error reported in APM when `_logger.LogError()` is called)
Remove the `UseAllElasticApm` from Program.cs
```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
```
Place the `UseAllElasticApm` in Startup.cs (Configure method)
```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
   app.UseAllElasticApm(Configuration); // or app.UseAllElasticApm()
   ...
}
```

Extended question : if we absolutely need to call this extension method on the `IHostBuilder` (Program.cs) how to provide the `iConfiguration` like its available on the `IApplicationBuilder` to feed the APM setting from any configuration provider like the appsettings.json ?

#### Expected behavior
Same behavior regardless of the `UseAllElasticApm` location

**Comment by NicolasREY69330** [comment]
Hello @z1c0 

after a lot of tries, I finally understood what causes the problem on my stack, if you take the sample of @gregkalapos and if in the Program.cs you add the Serilog extension, the error log stops creating error transactions

You'll need
```xml
<PackageReference Include="Serilog" Version="2.12.0" />
<PackageReference Include="Serilog.Extensions.Hosting" Version="5.0.1" />
```
and 
```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); })
		.UseSerilog() // <= here
		.UseAllElasticApm();
```

note the same behavior( (KO) occurs when you place the Apm method extension before the Serilog one
```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); })
		.UseAllElasticApm() 
		.UseSerilog(); // <= here
```

Not sure it's linked with the `UseAllElasticApm()` applied in Startup.cs or in Program.cs problem (my previous post) but sounds really strange to me.

Thanks for your help

**Comment by gregkalapos** [comment]
Hey @NicolasREY69330 

There are 2 thins here and as you point out in your last sentence, they aren't really related on the code-level, although the end result is exactly the same: error logs won't be captured as APM errors.


## Regarding the 1. comment:

on the `To Reproduce` part: what you describe is expected behaviour - in order to register the our `ILoggerProvider` implementation which captures the error logs as APM error, we need to have access to `IServiceCollection` - and from what I know it's only possible via the `IHostBuilder`. Btw this happens [here](https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm.Extensions.Hosting/HostBuilderExtensions.cs#LL94C5-L94C5). Under point 2 (where you register the agent in `public void Configure(IApplicationBuilder app, IWebHostEnvironment env)`) I think it's already too late too and we can't register our `ILoggerProvider` - at least that's what I remember.

In any case - with the setup under point 2 we don't turn on this feature. Thanks for pointing this out - I think we should better communicate this. But unfortunately I don't think this will change. 

> Extended question : if we absolutely need to call this extension method on the IHostBuilder (Program.cs) how to provide the iConfiguration like its available on the IApplicationBuilder to feed the APM setting from any configuration provider like the appsettings.json ?

No need to pass `IConfigurationReader`, the agent will just take whatever it's already there (another advantage to have access to `IHostBuilder`). So without passing it, you'll still have the exact same functionality: putting configs into `apsettings.json` will work - if not, then let us know, because this should work. 

## Regarding the 2. comment

Now this will be a bit more complicated, but in essence, the key issue is that calling `.UseSerilog()` erases our `ILoggerProvider` - in fact any logging provider and only registers serilog's own.

The issue with this is that I'm not sure we can do much about it, other than providing workarounds - one you describe is valid.

We already run into this before, and I had a longer internal write-up on it, here are all the details:

```
The essence of it: our .NET APM agent has this feature which turns logs on error level into an APM error and it shows those errors in the context of an APM Trace, so it correlates those error logs on the APM UI to traces/spans.

Once they turned on serilog integration to ship all their logs to elasticsearch, then the functionality described above broke… those error logs aren’t captured anymore as APM error events.

### Why is this happening?

The .NET mechanism that our agent uses to capture those error logs is to register an `ILoggerProvider` and that turns these error logs into APM errors. This happens behind the scenes when users call the `UseAllElasticApm` method.

Now; here comes my finding: when you register serilog to integrate with ASP.NET Core, the default method overwrites the existing `ILoggerProvider` instances - in our case, it simply removes our `ILoggerProvider` which implements the feature described above.

Here is a simple reproducer:

```
public class Program
{
  public static void Main(string[] args)
  {
    Log.Logger = new LoggerConfiguration()
      .Enrich.WithElasticApmCorrelationInfo()
      .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(esUrl))
      {
        //all the configs here
      })
      .CreateLogger();
    CreateHostBuilder(args).Build().Run();
  }

  public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
      .UseSerilog() //<-- this causes the issue... this needs to be changed! (details below)
      .UseAllElasticApm()
      .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
}
```


The issue is caused by the `.UseSerilog()` line… that removes our `ILoggerProvider` (and in fact any `ILoggerProvider` instances… it literally erases everything).

Now… that method comes from the `Serilog.AspNetCore` package, and that’s a community package, it’s not our code and not under our control. It’s in this repo: https://github.com/serilog/serilog-aspnetcore

### How can we (they) fix this issue?

There is an overload to that method which instructs `Serilog.AspNetCore` to not remove other `ILoggerProviders`. Here is an example how that would work:

```
public class Program
{
  public static void Main(string[] args)
  {
    CreateHostBuilder(args).Build().Run();
  }

  public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
      .UseSerilog( new Action<HostBuilderContext, LoggerConfiguration>( (h,l) =>
      {
        l.Enrich.WithElasticApmCorrelationInfo()
          .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(esUrl))
          {
             //all the configs here         
          });

      }) , writeToProviders: true) //<- this is the fix - make sure you flip this flag to true
      .UseAllElasticApm()
      .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
}
```

The key here is that instead of calling `.UseSerilog()`, I call another overload - it’s this one:

```
public static IHostBuilder UseSerilog(
 this IHostBuilder builder,
 Action<HostBuilderContext, LoggerConfiguration> configureLogger,
 bool preserveStaticLogger = false,
 bool writeToProviders = false)
```

and here I set the `writeToProviders` parameter to `true` (default is false) and that way it won’t remove all other `ILoggerProviders` - specifically it won’t remove the one from our agent.

There are some other overloads as well… obviously I don’t know their code and how exactly they configure serilog, but the key is: they’ll need to set this flag to true and from that point both the serilog sink and our feature to turn error logs into APM error events will work.

Now.. I’m not sure if we can offer an out-of-the-box solution, since this isn’t our code. We can definitely document this, but I’m not sure if we can do more than that. People in this repo could do more about this issue: https://github.com/serilog/serilog-aspnetcore

Hope this helps them.
```

That's my summer from when we ran into this first, but @NicolasREY69330 's workaround is actually much easier (just flip the order), although I haven't tested it myself.

**Comment by NicolasREY69330** [comment]
@gregkalapos many thanks for your awesome answer. I'm glad to see that I'm not the only one to have met this before and ended to the same conclusion.

> That's my summary from when we ran into this first, but @NicolasREY69330 's workaround is actually much easier (just flip the order), although I haven't tested it myself.


I'm sorry about it but flipping both extension methods ends to the same (KO) results
> note the same behavior( (KO) occurs when you place the Apm method extension before the Serilog one

I'll try your workaround. By the way, in this case, how do you initiate your loger ?
Currently I use something like in the Startup.cs:
```chsarp
Log.Logger = new LoggerConfiguration()
            .ReadFrom.Configuration(config)
            .Enrich.WithElasticApmCorrelationInfo()
            .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(configuration.ElasticSearchLog))
            {
                 //all the configs here  
            })
            .CreateLogger();
```
isn't it redundant with ?

```chsarp
...
      .UseSerilog( new Action<HostBuilderContext, LoggerConfiguration>( (h,l) =>
      {
        l.Enrich.WithElasticApmCorrelationInfo()
          .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(esUrl))
          {
             //all the configs here         
          });
      }) 
```

I'll do some tests next week and keep you informed. 
Many thanks

**Comment by NicolasREY69330** [comment]
@gregkalapos your trick works like a charm.
For my last question, forget about it, it's for the static logger, it's not relevant here.

**Comment by juliankock** [comment]
I would like to add some additional details:
I was doing the following 
```
Host.CreateDefaultBuilder(args)
    .UseSerilog((host, log) =>
    {
        log.Enrich.WithElasticApmCorrelationInfo();
        log.WriteTo.Console(new EcsTextFormatter(),
            restrictedToMinimumLevel: appSettings.LogEventLevel);
    }, writeToProviders: true)
    .UseAllElasticApm()
    .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
```
However, since the other examples didn't rely on Elastic ECS format being written to console, I saw duplicate logs. 

Doing the following before using `UseSerilog` helped:
```
Host.CreateDefaultBuilder(args)
    .ConfigureLogging(x => x.ClearProviders())
    .UseSerilog((host, log) =>
    {
        log.Enrich.WithElasticApmCorrelationInfo();
        log.WriteTo.Console(new EcsTextFormatter(),
            restrictedToMinimumLevel: appSettings.LogEventLevel);
    }, writeToProviders: true)
    .UseAllElasticApm()
    .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
```
That removes the default logger from ASP.NET Core. 

I hope it can help someone in the future.
