### ISSUE TITLE
[BUG] Stack traces are reported for ALL spans (< 5 ms)

### ISSUE THREAD

**Issue by z1c0** [elastic/apm-agent-dotnet#1949]
### APM Agent version

`1.19.0`

### Environment

https://release-oblt.kb.us-west2.gcp.elastic-cloud.com/app/home#/

### Describe the bug

All `dotnet` spans in this environment have stack trace data.
There is no evidence of `SpanStackTraceMinDuration` being configured, so spans with a duration below `5ms` should
not report a stack trace.

### To Reproduce

Here is an [example](https://release-oblt.kb.us-west2.gcp.elastic-cloud.com/app/discover#/doc/apm_static_index_pattern_id/.ds-traces-apm-default-2022.11.30-000019?id=7n2HCoUBuNAgYW1OrMzE) of such a span (look at the `JSON` tab).

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/4700296/207285944-7bf43cba-f7df-4a0f-8e2f-3dbaa6f4bc9d.png">

So far, the behavior could not be reproduced in a local dev environment.

**Note:** All `dotnet` spans in the environment where the problem occurs are of `span.type = db`, `span.subtype = sqlite`. This could be a clue.

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/4700296/207286795-7e7a6a7d-3e25-4aed-a8f0-19114ff5aa0d.png">

Also, see this [Slack thread](https://elastic.slack.com/archives/CDU88CX8W/p1670828400916659)

**Comment by gregkalapos** [comment]
There is an optional parameter to capture the stacktrace when the span is started (this is due to `async): https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm/Model/Span.cs#LL68

We do that in EFCore instrumentation: https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm.EntityFrameworkCore/EfCoreDiagnosticListener.cs#L41

But I wonder if we remove those if the span is less than the `SpanStackTraceMinDuration` 🤔  I don't think so... shouldn't it be here? https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm/Model/Span.cs#L471
