### ISSUE TITLE
Support scope

### ISSUE THREAD

**Issue by hollowimage** [elastic/apm-agent-dotnet#2]
Will this agent support .net core as well? and 2.1? 

.net core 2.x allows us to run code in linux on kubernetes, but thats not the same bowl of wax as classic .net. 

https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x
https://www.infoq.com/news/2017/10/dotnet-core-standard-difference

**Comment by gregkalapos** [comment]
Congratulation on opening the first issue! :) 

The short official answer is: we don’t have a final decision yet.

The longer answer is that we definitely aim to support .NET Core. This is on the top of our requirement list (including 2.1). If you look at the [prototype branch](https://github.com/elastic/apm-agent-dotnet/tree/prototype) you’ll find 2 .NET Standard libraries that work both on .NET Core (not only on Windows, but also on Linux and macOS, and basically everywhere where .NET Core runs) and also on Full framework versions that support .NET Standard.

We will see how it evolves, it’s still very early stage, so no final promises yet, but it’s definitely something we would like to support.

**Comment by gregkalapos** [comment]
In the meantime there is also a survey about this: https://goo.gl/forms/FHHbhptcDx8eDNx92

By filling it you give us very useful information on where we should focus, so every response on that is highly appreciated!

Since I think the question is answered I close this. Feel free to comment if there is anything left open here.
