### ISSUE TITLE
Tracking non-web transactions

### ISSUE THREAD

**Issue by xwrs** [elastic/apm-agent-dotnet#20]
Not sure if this functionality is planned, but it would be really nice to have an ability to track transactions which are not originated from HTTP requests in Asp.Net Core application. For instance there can be a Asp.Net Core microservice which is part of event-driven system. Requests in this case are coming from Event Bus and cannot be monitored as Web transactions.

**Comment by gregkalapos** [comment]
Thanks for bringing this up @xwrs.

This use case is definitely on our radar. We started working on ASP.NET Core support for HTTP requests since that seem to be the most common use case, but long term, of course we want to cover more use cases.

Regarding out of the box support for Event Bus I cannot give you any information, since we currently focus on ASP.NET Core + HTTP. On the other hand our goal is to offer a nice API very early for manual instrumentation. So you should be able to start a transition when the application reads something from Event Bus manually. Later of course out of the box support (without manual instrumentation) should be, and will be discussed. 

The other challenge will be to correlate the request to the initiating micro-service. This is another topic that is on our radar. 

I leave this issue open for now.

**Comment by gregkalapos** [comment]
A short summary about where we are regarding this topic:
- The [Pubic API](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html) offers methods that enable users to automatically start a transactions.
- [Distributed tracing support](https://github.com/elastic/apm-agent-dotnet/issues/14) will land soon, with that you can also "connect" multiple transactions into a trace. It's originally designed with HTTP, but if you pass the parent id through e.g. Event Bug then the transactions will be correlated into 1 trace - so with some minor tweaks you can use it to cover non-web transactions. 
- Auto instrumentation is planned for this kind of things in the future, but there are no specific dates and we don't even have issues, so that's in an early stage.

I close this now, feel free to comment if you have further questions.

**Comment by illegalnumbers** [comment]
Are there any plans on adding additional auto instrumentation for items like this? For example, it would be a really nice to have for services that maintain service bus connections to automatically setup transactions.
