### ISSUE TITLE
ASP.NET - create transaction name based on route and group by optional values

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#201]
The same as elastic/apm-agent-dotnet#84 but for Full Framework ASP.NET.

We will probably be able to do it automatically for ASP.NET frameworks that have routing such as MVC and WebApi. In addition we might also consider supporting manual configuration similar to the one implemented by Java agent - https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-url-groups

**Comment by gregkalapos** [comment]
We could use `HttpApplication.Context.Request.RequestContext.RouteData` in case it's an MVC model. If it's WebForms, I think it's reasonable to just use the `.aspx` page name.

**Comment by gregkalapos** [comment]
A bit more info here:
- Currently on ASP.NET Classic we generate transaction name purely on the url, so we create transactions with names like `/user/1`, `/user/2`, etc.
- On ASP.NET Core we do it according to the [spec](https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-http.md#http-transactions), so above 2 urls would be both called `/user/{userId}/`. 
- This behavior leads to transaction group explosion and it gets more important because for some server features it's really important to group those parametrized calls together
- The same logic for ASP.NET Core is [here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs#L316). We'd need that for ASP.NET Classic somewhere around [here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs#L116)
