### ISSUE TITLE
Use DiagnosticSource and activities instead of custom transactions

### ISSUE THREAD

**Issue by mikenorgate** [elastic/apm-agent-dotnet#21]
The `Activity` class of `System.Diagnostics.DiagnosticSource` is already designed for tracking code execution and is a similar idea to your `Span`. It would mean that the apm agent could just create diagnostic listeners for the scopes that you want to track.

The main benefit I can see from this is that it is built into and used by the framework, which means that I can track things inside the framework without needing custom code. i.e. all requests made by `HttpClient`. The other benefit is that AspNet already handles the distributed tracing aspect. If you set the `Request-Id` header and have a diagnostics listener configured it will automatically create an activity using the `Request-Id` as it's parent.

There is a whole bunch of documentation on using this here: https://github.com/dotnet/corefx/tree/master/src/System.Diagnostics.DiagnosticSource/src

**Comment by gregkalapos** [comment]
Thanks for bringing this up @mikenorgate, this is a very important topic. 

So, in short: we already do what you suggest here. 

More details:
The current prototype basically registers for `DiagnosticSource` events and based on those events we create `Transactions` and `Spans`. Specifically, this is our [listener for `HttpClient`](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListener.cs) you mention.

So for getting diagnostic information from the framework `DiagnosticSource` is what we currently use. Probably we'll see some limitations, since it's not present in older frameworks, for that we have to figure out something. Currently our focus is ASP.NET Core, so we have no problems there using `DiagnosticSource`.

On the other hand for manual instrumentation we don't plan to rely on `DiagnosticSource`. Currently the plan is that if you want to manually start a `Transaction` and create `Spans` then you will need to use our API. The main reason is that this API is very similar across all Elastic APM Agents and it's very well defined what you can and should capture within a `Transaction` and a `Span` (of course with options to put your own custom data into it). So if you within your application code create `Activities` with custom `DiagnosticSource` events then the agent won't listen to those, it only listens to specific framework events (like outgoing HTTP request, Database calls, etc.). Of course this is not a done deal, we are in a very early stage and happy to discuss.

The built-in distributed tracing support in ASP.NET Core is a very interesting point! I haven't thought about that, but it'll be definitely important. We'll come back to this when we start working on #14. Thanks for pointing that out!

I'll close this issue, since I think we have the same approach here. Feel free to reopen or simply comment if you think I can answer any other question.

Thanks again!
