### ISSUE TITLE
EntityFramework Core queries are not captured with Mysql provider

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#230]
While using https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql provider, 
EF queries are not captured by elastic-apm agent. 

![image](https://user-images.githubusercontent.com/3065048/57890337-0a721700-7840-11e9-9824-ba0e2db807d2.png)

The same code, but with npgsql works without any issues. 

Versions : 
- NetCore 2.2
- EFCore 2.2.3
- Pamello 2.2.0

Thanks,
Stas

**Comment by skynet2** [comment]
I found the issue, maybe somebody can explain that behavior @gregkalapos .

The issue is that there are two extension methods UseElasticApm; 

- Elastic.Apm.All.UseElasticApm - works (because it passes two default diagnostic subscribers)
- Elastic.Apm.AspNetCore.UseElasticApm - don`t work, because  it does not pass default subscribes, and params allow them to be empty

When i changed my code to use Elastic.Apm.All.UseElasticApm it started to work :)

**Comment by lafriks** [comment]
@skynet2 because `Elastic.Apm.AspNetCore.UseElasticApm` is meant to be used without EF to not add unneeded dependencies to projects not using EF.

Probably it would be good to rename it to `UseElasticApmCore` like it is done in .NetCore MVC there is method `AddMvcCore` that adds minimal feature set and `AddMvc` that adds full feature set.

**Comment by gregkalapos** [comment]
Yes, @lafriks's explanation is correct. 

- `Elastic.Apm.All.UseElasticApm`: This is in the `Elastic.Apm.All` package, which has all the other agent packages as dependency, therefore it registers all the listeners. This is the simplest and easiest to use, especially if you already have lots of dependencies and don't really care about adding some other packages as dependency to your app. So it's just 1 line and everything is registered.

- `Elastic.Apm.AspNetCore.UseElasticApm`: This is in the `Elastic.Apm.AspNetCore` package, and it only has some `AspNetCore` dependencies plus the `Elastic.Apm` base package. This is the best to use in case you want to have full control over your dependencies - and as @skynet2 points out this does not pull in the EF Core listener, in fact it does not really register any listener. If you use this then you have to manually select and register what you need, this way you can keep the additional dependencies minimal.

I agree that this is confusing, and I also think that we should consider renaming ` Elastic.Apm.AspNetCore.UseElasticApm`. I'm not sure about the name `UseElasticApmCore` - the word `core` is already very overloaded (other than that I'd take it...) Maybe `UseElasticApmBase`?

**Comment by SergeyKleyman** [comment]
`UseElasticApmBase` sounds good. Also `Elastic.Apm.All.UseElasticApm` can be renamed to something like `UseAllElasticApm` to make it clear that it will switch on (and thus create dependency on) all the features.

**Comment by gregkalapos** [comment]
Perfect, so we seem to agree that we should rethink the naming.

Since this issue turned out to be something different as it was originally, I opened #234 to discuss the new names (I think it's worth having its own issue for this to track that decision). 

I close this now, since the original problem is addressed. @skynet2 feel free to reopen if that's not the case and also feel free to comment on the other issue.
