### ISSUE TITLE
Rename Elastic.Apm.All project

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#243]
Now that we have code specific for .NET Core (`Elastic.Apm.AspNetCore` and `Elastic.Apm.EntityFrameworkCore`) and .NET Framework (`Elastic.Apm.AspNetFullFramework`) `Elastic.Apm.All` project still references only .NET Core projects. We should consider if we want the same kind `.All` project to include all features applicable to .NET Framework.

It seems that continuing with just one `.All` project and include both .NET Core and .NET Framework would not be very useful because most customers' projects target one of those platforms. So maybe we should have split the project tree at the very top:

| Current name | New  name | Notes |
| --------------- | ------------ | ------- |
| `Elastic.Apm.AspNetCore` | `Elastic.Apm.NetCore.Asp` | |
| `Elastic.Apm.EntityFrameworkCore` | `Elastic.Apm.NetCore.EntityFramework` | |
| `Elastic.Apm.All` | `Elastic.Apm.NetCore.All` | |
| `Elastic.Apm.AspNetFullFramework` | `Elastic.Apm.NetFramework.Asp` | |
| | `Elastic.Apm.NetFramework.EntityFramework` | New project (TBD) |
| | `Elastic.Apm.NetFramework.All` | New project. References `Elastic.Apm.NetFramework.Asp` and `Elastic.Apm.NetFramework.EntityFramework`) |

**Comment by gregkalapos** [comment]
I'm afraid, the proposed scheme with `NetCore` and `NetFramework` won't really work - or it'd be misleading, for example the EF Core package (proposed `Elastic.Apm.NetCore.EntityFramework`) also works with EF Core on Full Framework, so that package is not specific to a .NET Core and I expect having similar situation with other libraries later. You can also run ASP.NET Core on top of Full Framework (see [here](https://blog.codeinside.eu/2018/03/31/running-aspnet-core-2-under-the-full-dotnet-framework/)) - MS plans to drop this long term, but it works with the current version.

Also this would be a big big breaking change.

On the other hand I also think that we should address the issue with having useful `All` packages for common scenarios, and adding ASP.NET (Classic) support breaks our current naming. 

How about keeping all names as they are, except changing the current `Elastic.Apm.All` to something that better reflects its purpose and also add something similar for the ASP.NET Classic scenario?

**Comment by SergeyKleyman** [comment]
Sounds good - for now we can just rename `Elastic.Apm.NetCore.All` to something like `Elastic.Apm.NetCoreAll` and in the future if necessary we can add another `.All` project - something like `Elastic.Apm.NetFrameworkAll`?

**Comment by SergeyKleyman** [comment]
For now we agreed to rename `Elastic.Apm.All` to `Elastic.Apm.NetCoreAll` and created a follow up #336 to take care of Full Framework "All" umbrella project.

**Comment by gregkalapos** [comment]
Implemented in #371
