### ISSUE TITLE
Use warnings in AbstractConfigurationReader instead of errors

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#261]
In `AbstractConfigurationReader` when we can't pars something we print an error. Using warnings would be better, because these are all cases that we handle by using default values and there is no data loss or anything like that involved.

**Comment by SergeyKleyman** [comment]
I disagree - those events/conditions are errors because when they happen it means agent will not behave as configured by the user and possibly in quite significant way.

If by "data" in "data loss" you refer to monitoring data collected by agent then I agree those events are errors (as well IMHO :). If by "data loss" you mean agent causing *application data* loss or *application state* corruption those events are fatal/critical level events and agent should probably deploy fail fast approach and shut down the whole application to prevent further state corruption. But with the current approach of "agent as library" I don't see application data loss or application state corruption as much of an issue as with "agent as native profiler" approach. So we can discuss it when we get to those problems.

Could you please clarify why it's important to not have configuration parsing issues as errors? They happen very rarely (now only once) so it's not like those events will flood the logs. Not that I think frequent events cannot be errors (throttling should be used to prevent those events from flooding the logs) but I try to find pros of your proposal.

**Comment by gregkalapos** [comment]
I just felt that e.g. not being able to send a transaction, or when the user does something with a span that already ended are things that are suited for errors.

Falling back to a default value for a config setting is I think not the same level of problem and that is a typical use-case of warning.

This is I think a good overview: 
https://stackoverflow.com/a/2031209/1783306

The ASP.NET Core LogLevel doc is a little bit more abstract:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=aspnetcore-2.2#fields 


But ok, let's not do it, let's see what users say.
