### ISSUE TITLE
Allow to create custom Transaction and Span

### ISSUE THREAD

**Issue by IlyaAtGitHub** [elastic/apm-agent-dotnet#267]
We have in our system our own traces collection mechanism. So, we already have our Transactions and Spans in other structures, which include start/stop times. I'd like to have possibility to convert at run-time our traces to APM structures and to publish. So, we need something like new Transaction(..., startTime, stopTime). We can't inhere from your apm-agent Transaction class because it's internal. We could implement ITransaction interface, but couldn't publish it by PayloadSenderV2.
Current implementation of the PayloadSenderV2 (https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Report/PayloadSenderV2.cs) doesn't allow to report custom ITransaction/ISpan/IError classes because in the function ProcessQueueItems uses class type like "case Transaction _" and not interface type. Could it be changed to the "case ITransaction _" as well the same for ISpan and IError?

**Comment by gregkalapos** [comment]
Hi @IlyaAtGitHub,

thanks for reporting this. 

First I'd like to answer your question:

> PayloadSenderV2 doesn't allow to report custom ITransaction/ISpan/IError classes because in the function ProcessQueueItems uses class type like "case Transaction _" and not interface type. Could it be changed to the "case ITransaction _" as well the same for ISpan and IError?

The challenge here is that we have some required fields in some of the objects that we send to the APM Server. If the agent sends an event to the server where one of the required fields is not set, the server will reject this event, so we need to make sure that the agent sends everything that the server expects. Therefore I'm not sure it'd be a good idea to accept custom `ITransaction`, `ISpan`, etc. implementations - this is not set in stone, I just try to explain the challenges of this.

Also another related comment: we plan to offer a bridge (or some type of other implementation) with other widely used tracing libraries. Originally we thought about OpenTracing, but now that OpenTracing and OpenCensus are merged into OpenTelemetry, OpenTelemetry became more interesting. 

So with that: let's focus on your requirement:

Can you tell me more about your trace collection mechanism? Is it something completely custom, or is it a widely used library?

What do you collect? Is it just Transaction (or Span) with timing information, or do you also collect more, like incoming HTTP request/response details (what we have on our [Context](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Api/Context.cs)), or e.g. SQL queries in case of database calls, etc? 

Would it help you if we'd offer an overload on `StartSpan` and `StartTransaction` where you can just pass the timing information to the agent? Or do you need more than that?

**Comment by IlyaAtGitHub** [comment]
Hi Gergely,
Thank you for the answer. Regarding the required by the APM Server fields, I'd suggest to define all required fields in ITransaction/ISpan. There's probably a reason why part of them are defined in interfaces and part - in the implementation. I'd suggest also to have some common interface between ITransaction and ISpan, because Transaction seems is a kind of Span. The addition reason is that, as I saw, Span could has as a parent either Transaction or another Span.

Regarding our tracing. We has a logging system is based on Log4Net. The logs are used mostly for the system debugging, therefore logging entries include also a business data. The same logs are used also for performance analyzing. Each method call has two entries: before and after a method call, so they simple could be converted to Transactions/Spans. We consider to use APM as an alternative logs presentation system for debugging and performance analyzing. We evaluated Yaeger implementation of OpenTracing and would like to check how can we work with Elastic APM directly without converters. 
We collect our logs' data as objects and serialize asynchronously. But your implementation of Transaction and Span requires to provide times and string data synchronously. Therefore we thought about our proprietary Transaction/Span implementation. Suggested by you StartSpan/StartTransaction could be very helpfully if we could also set IDs (self, parent, transaction, trace), start/end times and data.

Best regards,
Ilya

**Comment by gregkalapos** [comment]
>  I'd suggest to define all required fields in ITransaction/ISpan. 

I think all required fields are already on the interfaces. Problem is that we can't force classes implementing those to have all fields filled. But I'm open for suggestions here.

>  I'd suggest also to have some common interface between ITransaction and ISpan, because Transaction seems is a kind of Span. 

Well, this already caused long discussions within our team :) so, yes a transaction is basically a span, it's just the 1. one in every request. Problem is that for the the APM server transactions and spans are different... those are different types and can evolve completely independently. Some other agents have a common interface and they already had difficulties when there were some changes on the server side. So currently we plan to keep it this way.

> We collect our logs' data as objects and serialize asynchronously. But your implementation of Transaction and Span requires to provide times and string data synchronously.

Could you maybe share some sample code for this? Something minimal that is close to what you do in your code. This sounds like a usecase for our public agent API, and maybe the easiest to solve this is just to build support for this use case instead of "fixing up" timing when you create your Spans and Transactions.

Also, how hard would be to make sure the agent calls the Span/Transaction start/ end  before and after a method call? Is that totally not doable?

**Comment by IlyaAtGitHub** [comment]
Our code could be explained shortly as following:

1. _logStructures = new ActionBlock<ILogStructure>(ProceedSingleLogEntry);
     creation of an Action block for log structure collection asynchronously 
2.      public void Add(ILogStructure logStructure)
        {
            _logStructures.Post(logStructure);
        }

     adding at run-time of log structures of the types:
     - Method call
     - Method return
     - Info in method body (optionally)
     - Error
3.     private void ProceedSingleLogEntry(ILogStructure logStructure)
        {
           // add log entry to Log4Net
           // Create/Close APM Transaction/Span/Error
        }
We prefer to create APM Transaction/Span/Error asynchronously on the step 3. Theoretically, we could start/end Span/Transaction on the step 2, as you asked, but your current implementation requires to define all additional information before Transaction/Span end. It would require from us data processing, serializations, etc. on the performance critical flows (2). We prefer to do it on the asynchronous flow (3). The best option for us would be to have a possibility to create Transaction/Span separately on the step 3 and provide all required data. Please consider it.

**Comment by IlyaAtGitHub** [comment]
What do you think? Could your framework be extended with the required by us possibilities? I could take a part in such implementation.

**Comment by gregkalapos** [comment]
Sorry for the super late response. 

There is some update that may be interesting to you.

I started playing with OpenTelemetry and I'm prototyping an exporter. It basically means that you can use the OpenTelemetry API and with a single line (or...well.. with very little) code you can direct the data to ElasticAPM through the .NET Agent.

Now this itself is not related to your problem, but in order to implement this, we basically need exactly what you request here.

OpenTelemetry offers an interface and it gives us all their span through this interface - it's the same story as yours - we have all the data in a different format and asynchronously we need to turn those into our format. The challenge is also the same - our current `Transaction` and `Span` objects are not designed for this and our `ISpan` and `ITransaction` also don't help.

This problem seems to be very relevant for multiple use cases. I don't have any timeline, it's in a super early phase, but I'll definitely keep your usecase in mind. 

My prototype is [here](https://github.com/gregkalapos/apm-agent-dotnet/tree/OpenTelemetryExporter). 

[This class](https://github.com/gregkalapos/apm-agent-dotnet/commit/4db6fd4c7ee82f26401bd4198511c4912c4d6fbc#diff-47c8ce6b9ebdbc3a6d94812cf5cf34c0R10) is something similar to what you need I guess. All that is currently temporary - it's just to get things working, but probably something similar will be needed and if we make that public I believe it'll also help you.

Again, I can't promise anything on this - but hopefully this helps you and once this gets more serious I'll definitely ping you.

**Comment by IlyaAtGitHub** [comment]
Gergely,
Thank you for the update. Yes, it's exactly what we need: public ITransaction, ITransaction and IError and that PayloadSenderV2 will get them in Queue... functions. Regardless to our requirements, I think that better to have an API is based on interfaces and not on implementations.
Please let me know when you'll decide about this direction. Meantime, we create some workaround, but I'd prefer to work with your API, so will wait for the update from you.
Ilya

**Comment by IlyaAtGitHub** [comment]
Hi Gergely,
Are any news when we could use apm-agent-dotnet with our custom Transactions/Spans/Errors/metrics? As was discussed, the only thing that prevents from it is that PayloadSenderV2 checks:
  case Transaction _:
  case Span _:
  case Error _:
  case MetricSet _:

instead of:
  case ITransaction _:
  case ISpan _:
  case IError _:
  case IMetricSet _:

Ilya

**Comment by gregkalapos** [comment]
> Hi Gergely,
> Are any news when we could use apm-agent-dotnet with our custom Transactions/Spans/Errors/metrics? As was discussed, the only thing that prevents from it is that PayloadSenderV2 checks:
> case Transaction _:
> case Span _:
> case Error _:
> case MetricSet _:
> 
> instead of:
> case ITransaction _:
> case ISpan _:
> case IError _:
> case IMetricSet _:
> 
> Ilya

Hey @IlyaAtGitHub 

Unfortunately this feature is not yet on the [next milestone](https://github.com/elastic/apm-agent-dotnet/milestone/6), so probably this will take some time.

Once we start working on OpenTelmetry, then I guess your use case will be also covered - but given OpenTelemetry is not yet GAd, we decided to not start working on it yet.

Sorry that i don't have better news on this.

**Comment by russcam** [comment]
Closing this issue in favour of #1521
