### ISSUE TITLE
Send service.environment (configured by user)

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#320]
See the [spec](https://github.com/elastic/apm-server/blob/master/docs/spec/service.json#L61)

We need it for remote configuration (https://github.com/elastic/apm-agent-dotnet/issues/190) - for details search `service.environment` at https://github.com/elastic/apm/issues/76
There also seem to be [other use cases](https://discuss.elastic.co/t/are-env-labels-supported-in-elastic-apm-agent/187556/3).

**Comment by vhatsura** [comment]
The quick question: what should we do in case of ASP.Net Core application? Environment name can be fetched from `IHostingEnvironment` and for me it's more conveninent way instead of custom environment name and configuration value. Also, in [specification](https://github.com/elastic/apm-server/blob/master/docs/spec/service.json#L61) environment isn't required and [other agent](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-environment) don't have default value. Is it ok if in case of ASP.Net Core application environment value always is set?

**Comment by SergeyKleyman** [comment]
As we discussed at https://github.com/elastic/apm-agent-dotnet/pull/393#discussion_r305362732 we can have .NET use case specific default if the option is not configured, even though other agents might not have default for this configuration option at the moment. Based on our discussions with other agents' devs, they might have defaults for these configuration options in the future.
Please describe for which use case (ASP.NET Core application, right?) and how is the value should be auto-discovered.

**Comment by rickardp** [comment]
If it can't be decided what default to use, IMHO I would suggest going forward and implementing the manually configured one first, leaving default empty.

The concept of environments is quite critical for the APM functionality in use cases where you have multiple environments (I suppose most users have at least a "test" and "production" environment).

**Comment by SergeyKleyman** [comment]
> If it can't be decided what default to use, IMHO I would suggest going forward and implementing the manually configured one first, leaving default empty.

i agree, this is definitely a valid approach.
