### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by DiegoTondim** [elastic/apm-agent-dotnet#359]
Hi guys,

I'm trying to use this agent in a web api, when I have just one endpoint and the average of requests is 3-4k/min. After few minutes I can see a visible delay to update the chart of transactions on Kibana dashboard. I have a cluster with 9 containers of APM, one dedicated server for Elastic Search and an ELB in front of APM. Everything is on AWS.

I was going further on the PayloadSenderV2.cs to understand what is happening, then I've found that after every transaction fire "_eventQueue.TriggerBatch()", then each transaction is one request to APM, by serial mode.

I've removed this "_eventQueue.TriggerBatch()" and added a ActionBlock<object[]> and the action has the same code from ProcessQueueItems. After the _eventQueue.ReceiveAsync I post the items to that worker that I setup with 1k parallel tasks. Now it's working fine.

I don't know if is the better solution, but I'm here to try to explain and discuss about that.

**Comment by gregkalapos** [comment]
Thanks for bringing this up @DiegoTondim! 

Just to make sure I understand correctly:
The issue is that transactions under your load (3-4K requests/min) sending transactions get delayed. Is my interpretation correct?

Your observation regarding `PayloadSenderV2` is correct: it starts a single thread and everything is done on this 1 thread. The thinking behind this is that we don't want to heavily effect the application, so we try to limit the number of threads that the agent uses.

But I can see how this can be the problem.

Regarding your solution with making `PayloadSender` using multiple threads: that's definitely 1 option - the potential problem here is that there is no upper limit on the threads/resources the agent can consume. I'm not rejecting the proposal, just stating it here.

I think there would be another option: we don't necessarily need the `_eventQueue.TriggerBatch()` when a transaction is finished. In fact that's there mainly to make small samples with 1-2 transactions work, in production that is indeed not optimal. 

Could maybe make another test to help us? Is yes, could you just revert the changes, remove the `_eventQueue.TriggerBatch()` from the `QueueTransaction(ITransaction transaction)` method and give the `BatchBlock` a bigger size, let's say 500, or 1000: 

```
private readonly BatchBlock<object> _eventQueue =
			new BatchBlock<object>(500);
```

Could you let me know if this helps? - feel free to change the `batchsize` if you see some impact and you think there is a better number.

This way the agent still uses only 1 thread to serialize and send the data, but it won't to it for every single transaction - instead it'll aggregate those. 

Thanks!

**Comment by DiegoTondim** [comment]
Yeah I can do that... but now, with a batch of 50 items, I get delayed with an smaller amount of requests.
The threads are limited to 1k in batches of 50. 
The performance of application was not affected.

**Comment by andrewharry** [comment]
Ideally the batch should be send when the min batch size is met or some kind of 'min time between sending' timer

**Comment by SergeyKleyman** [comment]
@andrewharry I agree, introducing 'min time between sending' should take care of "delayed with an smaller amount of requests" concern.
But we still need to find a way to deal with large amount of requests.
@DiegoTondim By "9 containers of APM" you mean that you have 9 APM servers that you would like to load balance, right? How many agents running simultaneously do you have? The reason I am asking is because I wonder which option describes your use case:
1. There are a lot of agents running simultaneously so it is okay if each agent sends data serially to only one APM server but load balancing multiple APM servers between agents should prevent APM servers from becoming a bottleneck.
2. There are few agents but each agent sends so much data that serially sending data to one APM server cannot accommodate and it's necessary for each agent to either load balance between multiple APM servers and/or multiple connections to APM server.

**Comment by SergeyKleyman** [comment]
I've created https://github.com/elastic/apm-agent-dotnet/issues/366 to improve this area of the agent.

**Comment by gregkalapos** [comment]
> Ideally the batch should be send when the min batch size is met or some kind of 'min time between sending' timer

I also thought about something similar when I worked on `PayloadSenderV2`, but haven't done that from 2 reasons: 
- as @SergeyKleyman says it solves the "min time between sending" problem, but I wasn't sure that this is a solution for huge load. It's true that we would not send every transaction by doing this though. That's definitely a plus. 
- Originally I thought that we do this per transaction - so we say each transaction is sent after x seconds (so having a guarantee on when each transaction is sent). But that's probably not the way to go and I'm not really sure there is a nice way to do this with `Taks.DataFlow`. On the other hand as mentioned in #366 there is the `FLUSH_INTERVAL` setting (seems to be [Ruby](https://www.elastic.co/guide/en/apm/agent/ruby/1.x/configuration.html#config-flush-interval) and Java only (not seeing the docs for Java, so not sure it's really in Java)) - that would be easy to do, it just says that each x seconds the agent sends whatever is queued up, plus some other agents also have that setting, which is again another reason to implement that.

To @DiegoTondim 
- > Yeah I can do that... but now, with a batch of 50 items, I get delayed with an smaller amount of requests.

So, increasing the queue number seems to help, right? I don't think 50 is big enough for serious load, but if increasing it helps, then probably a combination the`MAX_QUEUE_SIZE` and `FLUSH_INTERVAL` would help you and also keep our goal to send transactions without big delay under smaller load.
- >The threads are limited to 1k in batches of 50. The performance of application was not affected.

I assume this applies to your original approach. We need numbers on this. Don't wanna sound skeptical but I think spawning those threads and doing all this work will increase the CPU usage - of course the app can still have the same response time if the CPU usage wasn't on a critical level previous to the change. Happy to be proven wrong though :)

**Comment by SergeyKleyman** [comment]
Even if the decision will be to allow more than one uncompleted request to APM Server (which I think other Elastic APM agents don't allow but we need to make sure) we won't need more threads for this since it's I/O bound operation and `HttpClient` supports non-blocking (asynchronous) operations. We can have more than one ongoing request even with just one thread. I think [`System.Threading.Channels`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels) is better fit than `System.Threading.Tasks.Dataflow` for flow with asynchronous operations but it doesn't matter if we won't go with more than one request to APM Server option.

**Comment by DiegoTondim** [comment]
Hi guys,

just to give an update about my scenario and how I solved my problem:

application:
20k req/min (during 10min every 20min)
1 app endpoint -> 1-2 calls to other app

batch size: 50
limited to 1k threads

Application is sending the data and creating up to 50 threads, the response time from APM is fast so we don't need a lot of parallel tasks, I tried with batch size of 100 and limited to 100 threads and works fine as well.

I didn't know about the FLUSH_INTERVAL, the combination of MAX_QUEUE_SIZE and FLUSH_INTERVAL can fix that.

Do you have a date to release version 1.0.0?

**Comment by SergeyKleyman** [comment]
@DiegoTondim Thank you for the information and the update.

>Do you have a date to release version 1.0.0?

I'm sorry but we don't commit to certain dates for releases. One thing I can say for sure is that releasing 1.0.0 is our top priority at the moment :)

**Comment by SergeyKleyman** [comment]
We discussed possible approaches and agreed that
- short term solution is to add `MAX_QUEUE_SIZE` and `FLUSH_INTERVAL` configuration options (even though these options are not used anymore with Intake API v2 as described at https://github.com/elastic/apm/blob/master/docs/agent-development.md#batchingstreaming-data)
- and long term solution is to implement the approach described at https://github.com/elastic/apm/blob/master/docs/agent-development.md#batchingstreaming-data and deprecate `MAX_QUEUE_SIZE` and `FLUSH_INTERVAL`.

**Comment by wast** [comment]
Last 2 links are 404 now. Is there update on this?
