### ISSUE TITLE
Container info modularisation

### ISSUE THREAD

**Issue by RenaudGelai** [elastic/apm-agent-dotnet#373]
Hello,

We are setuping an ELK environment with APM for our production environment. We have a rather peculiar hosting solution. We do not have containers (did this before the rise of containers), but we have multiple instances of the same service, and each is identified by its unique id. So what we would like to do is give this id in the "container id" of the Agent to be able to use this in elk and discriminate data based on this id.

What i suggest is refactoring SystemInfoHelper to use an interface instead, and configure it with AgentComponents. SystemInfoHelper would of course implement this interface and would be the default value (non-breaking change). This will also allow to be more flexible with other container-based solutions.

I don't see any alternative to this except forking and maintain our own version of the agent.
We have planned a large-scale work to be able to use containers in the future, but we would realy like to be able to use this before.

I of course offer to implement this with a PR in the very near future.

Best regards.

**Comment by RenaudGelai** [comment]
Would also make #348 easy ;)

**Comment by axw** [comment]
@RenaudGelai as a general rule we stick to [ECS (Elastic Common Schema)](https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html).

Putting something that's not a container ID in the container ID field could be problematic. For example, when a container ID is found, in the APM UI we will use that to provide links for jumping to container logs (extracted by Filebeat) or metrics (extracted by Metricbeat). The container IDs need to be consistent across those different data sources, which would require also customising those Beats.

It sounds to me like you need way to specify the `service.id` (see https://www.elastic.co/guide/en/ecs/current/ecs-service.html). We don't currently have this in the service metadata, but I think it would make sense to add it. What do you think?

Alternatively, we have an open issue to add support for "global labels": https://github.com/elastic/apm-agent-dotnet/issues/183. Labels are arbitrary, user-specified key/value pairs that you can associate with your service's APM data..

**Comment by RenaudGelai** [comment]
Hello,

Will i be able to do the same things with service id ? (jump to logs, discriminate data in the search, ...)

If yes, that might be a solution for us, and i will be more than happy to integrate these changes ;)

**Comment by axw** [comment]
> Will i be able to do the same things with service id ? (jump to logs, discriminate data in the search, ...)

You would be able to filter on `service.id` in the search bar.

We don't currently have an action to jump to logs for a specific service instance, but it could make sense to add one. You could explicitly filter on `service.id` in the search bar in the Logs UI, though.

You would need also need to configure Filebeat using a processor (https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html) to either extract the `service.id` field from your log events, or otherwise enrich the logs using a static configuration (i.e. using an `add_fields` processor).

Even if you injected your service UUID into the container ID field for APM, you would still have to do this for Filebeat if you wanted to correlate traces and logs.

**Comment by axw** [comment]
@RenaudGelai it turns out I was wrong to suggest using `service.id`. That field is meant to have the same value for all instances of a service. Clarified here: https://github.com/elastic/ecs/pull/502

So unless you can use some other existing metadata for filtering, such as the host name, custom labels are probably the way to go.

**Comment by RenaudGelai** [comment]
Hello.

And what about the logs ?

**Comment by axw** [comment]
@RenaudGelai seeing as putting non-container IDs in the container info is not a change we're going to make, I'm going to close this issue.

If you can add labels to your APM data (https://github.com/elastic/apm-agent-dotnet/issues/373#issuecomment-512117577), and you can add labels to your logs (https://github.com/elastic/apm-agent-dotnet/issues/373#issuecomment-512638096), then you should be able to search on those labels in either the APM UI or Logs UI. I'm guessing that you don't run multiple service instances on the same host, so you could also just search in the APM UI on your label, and then use the "Show host logs" action to jump to that service instance's host logs.

If it's still unclear how you can use these to solve the problem, please open a forum post at https://discuss.elastic.co/c/apm. That's the right place to have conversations like this, and will get more visibility. Thank you.
