### ISSUE TITLE
Make `Span` and `Transaction` disposable? - Agent API design

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#38]
This issue is about a design decision and for discussion about this specific decision. Relates to #26.

To save time/space in the discussion we focus on `Span`, but the same discussion is valid for `Transaction`.

### Description of the current situation
The default pattern to wrap a particular piece of code into a span is this: 

```
var span = transaction.StartSpan("SampleSpan", Span.TYPE_DB);
try
{
    //code you want to capture as a span
}
catch(Exception e)
{
    span.CaptureException(e);
    throw; //don't use `throw e` to preserve the call stack.
}
finally
{
    span.End();
}
```

This is very similar to the [Java Agent API](https://www.elastic.co/guide/en/apm/agent/java/master/public-api.html#api-transaction-start-span).

Currently both `ISpan` and `ITransaction` offer a convenient method to start, stop spans/transactions and also to automatically report unhandled exceptions. The intention is to avoid having to write too many additional lines just to capture something as a span or transaction. 

So, the equivalent of the code from above with the convenient API is this:
```
transaction.CaptureSpan("TestSpan", Span.TYPE_DB, () =>
{
   //code you want to capture as a span
});
```
There are overloads for async methods, and also for methods with return value.

### Alternative solution, `IDisposable`
Lots of similar tools, like [MiniProfiler](https://github.com/MiniProfiler/dotnet) solve this by implementing `IDisposable`, and not by having a method that takes `Action` or `Func` as we do. Therefore some users may expect that our `Span` and `Transaction` types also implement `IDisposable` and disposing those would do basically the same as calling the `End()` method. 

With this the code would be something like this:
```
using(var span = transaction.StartSpan("SampleSpan", Span.TYPE_DB))
{
   //code you want to capture as a span
   //+ capturing exceptions somehow
}
```

Therefore: Should our `Span` and `Transaction` types implement `IDisposable`? 

#### Pros:

- Other tools do this ([OpenTracing C#  API](https://github.com/opentracing/opentracing-csharp/blob/master/src/OpenTracing/IScope.cs#L19), [MiniProfiler](https://github.com/MiniProfiler/dotnet)).
- Wrapping these kings of things into a `using` block seems very natural.
- `using` avoids closures, which we have with the methods taking a lambda. This can cause overhead in perf. critical scenarios due to allocations. (On the other hand the `StartX()` and `End()` combination still can be used to avoid this problem).

#### Cons:
- The `using` block only partially solves the problem: it can automatically call `End()`, but it does not capture unhandled exceptions. Actually tools that typically use `IDisposable` for similar things don't have a `catch(Exception e){capture(e)}` part in the pattern that they simplify with the `using` block. So having the `using` block plus an additional exception handling logic would make the API more noisy than the plain, original API from the beginning of the discussion. 
- In the original API ending a span happens by calling the `End()` method, and this is common across all agents. If we implement `IDisposable` then we will call the `End()` method from the `Dispose()` method and from that point we basically have 2 methods that end a span, and that does not feel right. The current API does not have this confusion.
- Adding `IDisposable` is a pattern to wrap unmanaged resources. We don't really wrap unmanaged resources here. So automatically calling the `End()` method is a similar problem to the problem that `IDisposable` solved, but it's not the same. See [`IDisposable` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netframework-4.7.2) : "Provides a mechanism for releasing unmanaged resources." That's not what we do by calling `End()`.

Currently we don't implement `IDisposable` and that seems to be the better decision, but this can be of course revisited. Happy to hear opinions!

**Comment by Mpdreamz** [comment]
In your first example, I think we should prefer `throw` over `throw ex` to re throw.

I think having both would be a very valid option. 

* **lambda** wraps/catches exception and closes the span
* **using** simply closes the span let the truly exceptional bubble out. You lose the chance to log it on span but that could be fine given a global handler still logs it on the transaction. I think this is a totally fine and dogmatic pattern for .NET.

**Comment by gregkalapos** [comment]
Good catch on the first sample, it should really be `throw`. I fixed that.

I also think it's a valid approach to have both, I'm just not sure that adding `IDisposable` would really add value - we should not forget that having both makes the API a little bit more complicated (we need to explain which one to use, etc.). It would be nice to have more feedback from users to see if it's worth adding the complexity. But the option for having both is totally open and we can add `IDisposable` at any time.

Regarding  
> let the truly exceptional bubble out
That's very important, and [that's already the case](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Api/ElasticApm.cs#L80) with the current lambda based implementation. It uses an exception filter to observe the exception, but it does not catch the exception, so the original exception will bubble up.

**Comment by gregkalapos** [comment]
For everyone not being happy with the decision above: We can reopen this any time. It'd be especially useful for us to hear what you think about the "cons" from the description.

**Comment by gregkalapos** [comment]
Reopen to maybe reconsider.

See also https://github.com/elastic/apm-agent-dotnet/issues/488

**Comment by gregkalapos** [comment]
We discussed this again, and still the cons outweigh the pros. Happy to hear specific reasons and more const if something was still not yet discovered.

**Comment by Mpdreamz** [comment]
@gregkalapos mind doing a small write up of the discussion?

**Comment by gregkalapos** [comment]
> @gregkalapos mind doing a small write up of the discussion?

@Mpdreamz there was nothing really new discussed, I basically just summarized the pros and cons and we agreed the const are stronger. 

Maybe 1 new thing that came up was that @axw had an idea to maybe create a new class that supports `IDisposable`, and we could offer using `using(...)` on that new class.

**Comment by gregmac** [comment]
I am brand new to using this, but it definitely felt very off this wasn't using `using`. 

### Another pro

* You can use [C#8 using declarations](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using) to very easily add spans with a single line change, without wrapping code in braces, eg:
```
using var span = transaction.StartSpan("SampleSpan", Span.TYPE_DB);
```
I've used this with great effect in the past adding MiniProfiler to a legacy application: I was specifically interested in profiling some slow, multi-hundred-line, badly-indented monstrosities of functions, and this let me create a readable pull request. Wrapping in braces would have meant a ton of whitespace noise in the PR plus having my name forever stuck on the `git blame` of that awful code.

### Arguments against cons

> * The using block only partially solves the problem: it can automatically call End(), but it does not capture unhandled exceptions. So having the using block plus an additional exception handling logic would make the API more noisy than the plain, original API from the beginning of the discussion.

I'd still argue it's less noisy, because it's one less line of code:

```
using var span = transaction.StartSpan("SampleSpan", Span.TYPE_DB);
try
{
    //code you want to capture as a span
}
catch(Exception e)
{
    span.CaptureException(e);
    throw; //don't use `throw e` to preserve the call stack.
}
```

In the case of nested spans -- especially if you are doing this in nested functions, which is the natural use case -- you can ignore the exception while letting it be caught by a higher span or at the transaction level.

There's also a [trick to detect exceptions](https://ayende.com/blog/2577/did-you-know-find-out-if-an-exception-was-thrown-from-a-finally-block), though it feels a bit hacky.

The logic in the `Dispose()` handler could basically be:
```
void Dispose() 
{
    if (!this.Ended)
    {
        // exception happened, but wasn't captured -- mark it for reference
        if (Marshal.GetExceptionCode()!=0 && !this.CapturedException) CaptureException(new UnknownException()); 
        
        End();
    }
}
```

---

> * In the original API ending a span happens by calling the End() method, and this is common across all agents. If we implement IDisposable then we will call the End() method from the Dispose() method and from that point we basically have 2 methods that end a span, and that does not feel right. The current API does not have this confusion.

As a .NET developer, I don't understand why this would be confusing, as it's quite a common pattern in many objects that implement IDiposable -- for example [System.Data.SqlClient.SqlConnection.Close](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.close?view=dotnet-plat-ext-6.0#remarks). The comments there state "Close and Dispose are functionally equivalent" and adding that to the docs would help.

See also in my code sample above, I added an `Ended` property to track if `End()` was called manually and not call it twice.

---

> *  Adding IDisposable is a pattern to wrap unmanaged resources. We don't really wrap unmanaged resources here. So automatically calling the End() method is a similar problem to the problem that IDisposable solved, but it's not the same. See [IDisposable documentation](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netframework-4.7.2) : "Provides a mechanism for releasing unmanaged resources." That's not what we do by calling End().

Arguing semantics, I think it _is_ what this does. A "Span" is pretty much an unmanaged resource -- even if it's not consuming an actual resource like a socket or file handle. 

Practically speaking, it's a widely-used convention in .NET, and frankly, not having it makes this feel like an API from the early 2000's. [This answer links to a lot more debate](https://softwareengineering.stackexchange.com/a/344504/34078) (both for and against) than I can cover.
