### ISSUE TITLE
Investigate failing HttpClientStackTrace in CI

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#381]
See https://github.com/elastic/apm-agent-dotnet/pull/374#issuecomment-512211365

**Comment by gregkalapos** [comment]
Current summary:

- It is not related to the pdbs - we seem to have those in CI
- It is related to the PR - branched from master and added logs - it works there
- Probably relevant change: previously we captured the stack trace in the `.ctror` of `Span`, now we do in in `Span.End()`. 
- When I change the PR to capture the stactrace in the ctor it seems to work - the test is green again in  CI
- Still cannot repro the failure locally

**Comment by gregkalapos** [comment]
This commit message shows the fix and some more explanation: https://github.com/elastic/apm-agent-dotnet/pull/374/commits/d8f761a6f0eeeb107c8a87fb87bc1110d0453957

**Comment by SergeyKleyman** [comment]
Sorry if I am missed that part in the explanation but I'm still not clear as to why there are no line numbers for stack traces captured at span's end. My concern is that now that we capture stack traces for spans only on span's end wouldn't it cause all span's stack traces to miss line numbers? Since we still don't know what at CI environment that causes it isn't it just as probable that it will happen at the customers environment?

**Comment by gregkalapos** [comment]
Making a span async also does not fail in CI - so far only the outgoing HTTP call repros this only in CI.

**Comment by gregkalapos** [comment]
Also tested within a linux docker container (similar to CI) - still no repro, the test with the `HttpClient` call still contains line number.

**Comment by SergeyKleyman** [comment]
I drew your attention to potential risk - it's up to you to decide if the risk is high enough to warrant additional effort or not.

**Comment by gregkalapos** [comment]
I think this is not a blocker - it's an optional field with known scenarios where it remains unset.
