### ISSUE TITLE
Exclude Urls from Tracing

### ISSUE THREAD

**Issue by andrewharry** [elastic/apm-agent-dotnet#434]
I am currently using (abusing?) a feature of the multiple server urls in order to exclude some urls from the tracing mechanism by specifying the excluded urls after the APM Server url

https://github.com/elastic/apm-agent-dotnet/blob/61ee66e1988da987af267005a5b006b80252f6e7/src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs#L199

**BUT**, I understand that this is against the intent of the ConfigurationReader.ServerUrls.
Can we have an explicit blacklist/exclusion mechanism?

FYI - my use case is to exclude the elastic logging from the tracer

**Comment by SergeyKleyman** [comment]
Yes, using `ServerUrls` for this purpose is definitely very fragile and can be easily broken. For example we might switch to Elastic APM Java agent's approach and instead of filtering by URL, not trace anything (include outgoing HTTP requests) occurring on threads created and used by .NET agent for internal purposes (in particular payload sender thread). This change in implementation will break your use case for `ServerUrls`.

We'll sync up with the other Elastic APM agents on the approach to this feature and update.

**Comment by SergeyKleyman** [comment]
One of the proposals to handle this use case is to extend agent's public API
```
Agent.Tracer.CurrentTransaction.PauseCreatingNewSpans();
// ...
Agent.Tracer.CurrentTransaction.ResumeCreatingNewSpans();
```
which you can add to entry/exit of your logging methods. This approach assumes that you can change the source code for the methods doing "elastic logging". WDYT?

**Comment by andrewharry** [comment]
Thanks for the reply.  I will experiment around with your suggestion and see how it goes

**Comment by SergeyKleyman** [comment]
@andrewharry I just wanted to make sure there is no misunderstanding - `PauseCreatingNewSpans`/`ResumeCreatingNewSpans` API mentioned above doesn't exist yet. I was just proposing it as an alternative to your originally proposed solution of introducing a new configuration option. That is why I wanted to get your feedback if it's an alternative that might work for you. If it doesn't then we will go back to considering a new configuration option.

**Comment by SnirCm** [comment]
Any update about this feature?

**Comment by shubhamranjan** [comment]
Any plans to implement this ? The golang sdk has this though: https://www.elastic.co/guide/en/apm/agent/go/current/configuration.html#config-ignore-urls
