### ISSUE TITLE
Difficulties with integration of Elastic.Apm to .Net Core console apps

### ISSUE THREAD

**Issue by vhatsura** [elastic/apm-agent-dotnet#458]
**Is your feature request related to a problem? Please describe.**
In the era of microservices a lot of services are creating as simple .Net Core console apps: message handlers, batch jobs.

From monitoring perspective  it would be nice to monitor such applications with Elastic APM, however, it's unable to achieve it right now: `Elastic.Apm.AspNetCore` cannot be used due to integration is performed with `IApplicationBuilder`, which is available only in Asp .Net  Core applications. The issue can be solved by manual configuration of Elastic.Apm agent except of reading configuration values from `appsettings.json` due to `MicrosoftExtensionsConfig` is internal class.

**Describe the solution you'd like**
As a short term solution `MicrosoftExtensionsConfig` can be mark as public, but it seems as a workaround. In addition, manual setup is still needed.
As a  long term solution, it would be nice to add additonal extension method on [`IHostBuilder`, which is introduced in .Net Core 2.1](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2) and became as [default builder for console and http-based applications in .Net Core 3.0](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0).

**Comment by vhatsura** [comment]
@SergeyKleyman. @gregkalapos, it would be nice to hear your thoughts about it. It will allow to move into right direction with necessary changes.

**Comment by SergeyKleyman** [comment]
@vhatsura Yes, I agree with you - configuration part agent's public API is problematic at the moment. The only way to provide custom configuration source is by implementing `IConfigurationReader` interface but if any application will actually try to do it we will break them every time we add a new property to `IConfigurationReader`.

I currently work on Remote (AKA Central) configuration feature https://github.com/elastic/apm-agent-dotnet/issues/352 and part of the implementation I changed what is now `IConfigurationReader` to be almost identical to `Microsoft.Extensions.Configuration.IConfiguration` in that it's just "string to string read only map". Then we can easily make `MicrosoftExtensionsConfig` public because it will nothing more than a very thin adapter.

**Comment by vhatsura** [comment]
@SergeyKleyman, yes, it make sense to wait remote configuration feature. However, even with remote configuration manual setup of agent will be needed. Does it make sense to add `Elastic.Apm.NetCore` package with extension method on `IHostBuilder`?

**Comment by gregkalapos** [comment]
I also agree that this is an important use case and we should have a good story for this. 

To make sure we are all on the same page, I’d like to summarize where we are today:

You can use the Agent API without any configuration, so somewhere in your code you can just write `Agent.Tracer.StartTransaction(…)` and the Agent will send the transaction. In this case the agent is initialized with defaults that we thought make sense, e.g. it will read configs through the `EnvironmentConfigurationReader` and it’ll log to the console. 

In case you want to change this you need to setup the agent, this is a 1 liner (plus the config you need) - this is not the config settings (like the ones you configure with environment variables). So this would be:

```
Agent.Setup(new AgentComponents(...pass your things here));

```

With this you can tell the agent what config-reader, logger, payloadsender, etc. to use.

Additionally in order to enable diagnostic listeners you can call

```
Agent.Subscribe(…pass the listener here);

```

any time in the app.


So, this is where we are today, worst case you need 2 lines to configure the agent. I’m not sure we can get rid of these 2 with reasonable effort. Happy to take opinions on this one. Is it very bad? If yes, why? Problem is, we need to read configs through environment variables everywhere, since `appsettings.json` is very .NET Core specific, so we can’t make that to our default.

Regarding the `appsettings.json` file:

Yeah, this is definitely an issue we have currently, if I remember correctly there was already a discussion that this should be public and not tied to our ASP.NET Core project - I tend to agree with, I guess it’d be beneficial to make it public - but I’m not sure where to put it… happy to take opinions on this, too.

Now, in case it’s be public and you’d want to use it we’ll still need to somehow pass it to the agent. 2 options here:

- Either we somehow do it automatically (I don’t really see yet how this would work, but maybe we can do this).
- Everything remains and you just simply pass it to to the `Agent.Setup` method - this is easy to do and not a big change.


Now to `IHostBuilder`

Yeah, I think that’s an awesome idea, that would enable us to do this on a very nice way - and we could in that case automatically use the `MicrosoftExtensionsConfig` too. My only concern is that it exists from .NET Core 2.1 and I guess in 3.0 you can still have a console application without it - so in other words we’d not cover every scenario with it. 

How about an `IHostBuilder` extension method plus keeping our current method (`Agent.Setup` and `Agent.Subscribe`) - with that we have a nice story for `IHostBuilder` and then with `Agent.Setup` we’ll still cover everything else.


Regarding Sergey’s comment:

I’m not sure the `IConfigurationReader` redesign itself addresses this problem. I think the key point here is to offer a ready to use config reader for `appsettings.json` which we already have - it’s the `MicrosoftExtensionsConfig`, we just need to make it public and provide a nice way to turn it on.

So, in my opinion next steps would be:

- Make `MicrosoftExtensionsConfig` public and move it to somewhere else - currently it’s part of our ASP.NET Core package, but probably you don’t want to reference that in simple console apps.
- Decide where to put the `IHostBuilder` extension method (Is `Elastic.Apm` a good fit? Will it still work with 2.0 without additional reference?) 
- Implement the `IHostBuilder` interface and make sure it’s integrated with the newly public `MicrosoftExtensionsConfig` well.

Thoughts?

**Comment by SergeyKleyman** [comment]
@vhatsura
Yes, I agree it make sense to make a parallel much smaller change to address a your problem which seems to have smaller scope. So if you would to submit a PR even before work on remote configuration is completed. As long as your change doesn’t preclude more generic use case (which sounds like it shouldn’t).

I would also recommend as part of PR including usage of the API you propose in sample command line app we have.

**Comment by connorads** [comment]
Was there any progress on a simple `IHostBuilder` compatible way of enabling the Elastic Apm Agent?

If not, what workaround did you end up using? @vhatsura

**Comment by vhatsura** [comment]
@connorads, you can track a progress in #537. Only yesterday I returned to such a thing and started to polish code. As for workaround, yes I have it for our current services. It's very simple:
1. Copy-paste `AspNetCoreLogger`, `AbstractConfigurationWithEnvFallbackReader` and `MicrosoftExtensionsConfig` into your code.
2. Register `IApmLogger`, `IConfigurationReader` and `AgentComponents` into dependency injection container:

```csharp
var builder =  Microsoft.Extensions.Hosting.Host.CreateDefaultBuilder()
    .ConfigureServices((ctx, services) => {
        services.AddSingleton<IApmLogger>(serviceProvider =>
                new AspNetCoreLogger(serviceProvider.GetService<ILoggerFactory>()));

        services.AddSingleton<IConfigurationReader>(serviceProvider => 
            new MicrosoftExtensionsConfig(ctx.Configuration, serviceProvider.GetService<IApmLogger>(),
                ctx.HostingEnvironment.EnvironmentName));

        services.AddSingleton(serviceProvider =>
            new AgentComponents(serviceProvider.GetService<IApmLogger>(),
                serviceProvider.GetService<IConfigurationReader>()));
    });
```

3. Before running your host, configure ApmAgent via static API:

```csharp
var host = builder.UseConsoleLifetime().Build();

var agentComponents = host.Services.GetRequiredService<AgentComponents>();

Agent.Setup(agentComponents);
using var _ = Agent.Subscribe(new HttpDiagnosticsSubscriber(), new MongoDiagnosticsSubscriber(), 
    new SqlClientDiagnosticSubscriber());

await host.RunAsync();
```

So, I know, it's not very simple and beautiful. Also, with agent update, this code can be broken and need to be updated due to some parts marked as internal classes and can be changed. However, right it's only one possible way for me to use it with proper logger and configuration reader setup.

**Comment by connorads** [comment]
Thanks that's great @vhatsura appreciate the detailed update!

**Comment by giotabidze** [comment]
Hi, any updates on this? @vhatsura I see failed checks on commits here #537 

Do you continue working on that?

**Comment by vhatsura** [comment]
Hey, @giotabidze.
At the moment, I'm concentrated on #661 to make an apm agent that can be used in self-host .NET Framework applications.
As for, #537, it would be nice to hear feedback from @gregkalapos before moving forward

**Comment by giotabidze** [comment]
@vhatsura Thanks for response

**Comment by gregkalapos** [comment]
I think this is done - #537 implements it - thanks for the work @vhatsura. There are some related issues still open and probably there will be some follow up PRs on the topic, but overall the use-case is already covered and merged.

If something important is missing please check if there is already an issue for that and if not, feel free to either comment here.
