### ISSUE TITLE
Elastic APM v1.1 release modified date issue

### ISSUE THREAD

**Issue by DaveChang24** [elastic/apm-agent-dotnet#527]
**Describe the bug**

Update elastic Elastic.APM to v1.1, the last step of our build is to package the build but it crashes out due to 

> The DateTimeOffset specified cannot be converted into a Zip file timestamp.
> Parameter name: value
> An error occurred when executing task 'Package'.
> Error: One or more errors occurred.
>         NuGet: Process returned an error (exit code 1).

I've checked our project build elastic dll as well as the NuGet available for download under the GitHub release tab. All the elastic APM dlls there are missing the modified date which seems to be the cause fo this issue.

Can you have a look at this problem?

Regards Dave

**To Reproduce**
1. Include latest elastic apm 1.1 nuget in project
2. build and run nuget pack that will attempt to zip the build 

**Expected behavior**
1. elastic dll has last modified date
2. nuget pack is successful

**Comment by gregkalapos** [comment]
Thanks for reporting this @DaveChang24.

I'm looking into this. 

Yes, the modified data is not correct:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/1091853/66125461-45a29600-e5e7-11e9-951e-d811c889d44f.png">
 
This seems caused by a nuget bug: https://github.com/NuGet/Home/issues/7001

**Comment by gregkalapos** [comment]
Also, just to state the obvious here: Probably the only way to fix this will be to release a new version, which'd be `1.1.1`.

**Comment by gregkalapos** [comment]
@DaveChang24 I just pushed a [new release](https://github.com/elastic/apm-agent-dotnet/releases/tag/1.1.1) addressing this issue. The latest version number with the fix is `1.1.1`. The packages are also updated on nuget.org (it may take some time for them to became visible, but should happen very soon). 

Could you maybe verify for us that the fix indeed solves the problem?

Thanks, and sorry for the trouble.

**Comment by DaveChang24** [comment]
The packaging step is working now :)

Thanks for the quick response 👍
