### ISSUE TITLE
Elastic.Apm.EntityFramework6 Package missing from Nuget

### ISSUE THREAD

**Issue by lucasfolino** [elastic/apm-agent-dotnet#595]
I am trying to setup APM for our dotnet project and the package Elastic.Apm.EntityFramework6 is missing from nuget.  Is this discontinued or is there another way to get telemetry for EntityFramework using the base dotnet package?

**Comment by gregkalapos** [comment]
Hi @lucasfolino 

That package is not yet released. It will be out with our next release. 

I know it's already in our `readme.md` here in the repository, but that's just because we already merged it into `master`. 

[Our official documentation](https://www.elastic.co/guide/en/apm/agent/dotnet/current/supported-technologies.html) is what we aim to keep in-sync with the latest release, so that is the best place to look what is already released.

Closing this since probably there is not more to do. Feel free to reopen if you need more help.
