### ISSUE TITLE
APM .NET Agent don’t Capture Http Status 2xx 

### ISSUE THREAD

**Issue by luisfernandomoraes** [elastic/apm-agent-dotnet#651]
**Describe the bug**
When uploading the application by running docker-compose up, a request that returns status 2xx such as http://localhost:xxxx/hc is not being captured by the APM agent but a request that returns a 404 for example http://localhost:xxxx/foo/bar is being logged by APM.

**To Reproduce**
1. clone repository from https://github.com/luisfernandomoraes/Way2CodeChallenge
2. Then call http://localhost:xxxx/hc 
3. Then do http://localhost:xxxx/foo/bar
4. See Kibana APM

**Expected behavior**
Show the http requests with status 2xx.

**Comment by rabberbock** [comment]
Same experience here, but I am using .net core 3.1.

**Comment by luisfernandomoraes** [comment]
Yeah, I've tried the .net core 3.1 too 😑

**Comment by willsilvano** [comment]
Same here.
I also noticed that POST requests are not being captured.

**Comment by gregkalapos** [comment]
@luisaantonio I looked at your sample app and I think the problem is that the APM Agent is not registered as the 1. middleware [here](https://github.com/luisfernandomoraes/Way2CodeChallenge/blob/master/Way2.CodeChallenge.Api/Startup.cs#L100). 

The `app.UseAllElasticApm(Configuration);` should be the 1. line in the `Configure` method, otherwise the APM middleware does not have a chance to capture the request before it hits MVC, or any other Middleware.

**Comment by willsilvano** [comment]
@gregkalapos Thanks! 
Your tip solved the problem here.

**Comment by gregkalapos** [comment]
Great, thanks for the quick feedback.

I looked into our [docs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup.html), and as it seems we don't document this properly. I'll add this to the docs!

**Comment by luisfernandomoraes** [comment]
Thanks @gregkalapos!! 
Problem solved here too.
