### ISSUE TITLE
Body sentinizer ignores everyting except string

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#656]
**Describe the bug**
Starting from 1.2.0 "Sentinize" attribute was added to **Body**.
So now, it starts to use BodyStringSanitizerConverter.

According to logic inside that class "if not string - write null" but Request.Body is object, so value of Request.Body can be anything (as a rule, in my case Dictionary<string,object>)

https://github.com/elastic/apm-agent-dotnet/blob/ac1b55cf937e15016fd939dc85ecf8aba367efcf/src/Elastic.Apm/Report/Serialization/BodyStringSanitizerConverter.cs#L52

**Expected behavior**
Request.Body should not be limited to be string only.

cc @gregkalapos 
Thanks,
Stas

**Comment by gregkalapos** [comment]
Hi Stas,

we know the current sanitizer logic is not correct - [This PR](https://github.com/elastic/apm-agent-dotnet/pull/617) would improve it, but it did not make it into 1.2. 

> Expected behavior
> Request.Body should not be limited to be string only.

There is already an issue for this: https://github.com/elastic/apm-agent-dotnet/issues/555 

The only thing to keep in mind is that having `object` on the public API can be super dangerous. If you put something into it that cannot be json serialized then there will be an exception thrown and we won't be able to send that data to the server - or we need to handle it somehow in a converter, and having `object` is basically impossible to handle.

As discussed in #555 probably `string` and `Dictionary<string, string>` would be the way to go - so, yes, we should not limit it to string, but unfortunately we won't be able to allow anything (meaning having `object` there) without having all the problems.

Now, to sanitization: if you look at #617 I think it's clear that sanitizing the body during serialization is super challenging - I think all other agents only sanitize `application/x-www-form-urlencoded` body. When we read the body we have this info, and also in ASP.NET Core, `application/x-www-form-urlencoded` body is already parsed into key value pairs, so it'd be very easy to do the sanitization when we read the data - it's hard when we try to sanitize during serialization, because we don't have the  content type.

So, the idea is that we could either flow the content type into the sanitization logic, or do the sanitization before we set the content type - the second is I think easier. This'd mean that if someone sets the body manually through the public API and we don't have the content type then realistically we won't be able to correctly sanitize the body - at least after some iteration I'd say implementing it is fairly hard and it'll definitely cause overhead.

So, the point is: I think long term we should get rid of the `object` and come up with something that can store the body in a meaningful way - probably something that is either `string` or `Dictionary<string,string>`. 

Furthermore if you set the body manually through the API, probably the best way for us to not sanitize it and leave the sanitization for the users - theoretically we could easily sanitize `Dictionary<string,string>`, but not `string` - sanitizing `string` is very hard.

This is not a final thing, these are just my thoughts on this topic after already sending a couple of iterations on it. 

Happy to take feedback.

**Comment by gregkalapos** [comment]
Addressed in https://github.com/elastic/apm-agent-dotnet/pull/712
