### ISSUE TITLE
SanitizeFieldNames parameter seems to be not working in .net core application

### ISSUE THREAD

**Issue by ghodasarakartik** [elastic/apm-agent-dotnet#716]
**Describe the bug**
I want to sanitize some of the route parameter (for ex. name) in my api.

API url is like {{APIUrl}}/api/v1/controller/action/{name}

**To Reproduce**
In my Startup, I've used UseAllElasticApm middle ware in StartUp.cs

![image](https://user-images.githubusercontent.com/6263711/73817510-18722880-4811-11ea-9b28-31865e279320.png)

I've set sanitizedfieldname param like below, although API is coming in the transactions list on APM but param is not being sanitized

![image](https://user-images.githubusercontent.com/6263711/73817572-4ce5e480-4811-11ea-8102-123c23e62a0e.png)
 

Please suggest if I am doing anything wrong here.

**Comment by gregkalapos** [comment]
Hi @ghodasarakartik,

Sanitization does not apply to values in the query string - this is also mentioned in the [documentation](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-core.html#config-sanitize-field-names).

The main reason we do not sanitize it is because it is considered non-sensitive - so usually what we suggest (based on suggestion from others) is that you should not store sensitive data there.

**Comment by ghodasarakartik** [comment]
Hi Gergely,

Thanks for a quick response.

I just show I need to update an URL as controller & action was not there but these are the route parameters and not query string. so that is not supported as well?

**Comment by gregkalapos** [comment]
> Hi Gergely,
> 
> Thanks for a quick response.
> 
> I just show I need to update an URL as controller & action was not there but these are the route parameters and not query string. so that is not supported as well?

Yes, maybe I should have said "everything that is in the URL" instead of query string. So yes, as long as it is in the URL - and from what I know route parameters are always coming from the URL - the agent won't sanitize it.

**Comment by ghodasarakartik** [comment]
Thanks Gergely for clarifying, I think that answer my question.
