### ISSUE TITLE
Elastic.Apm.SqlClient Nuget is not available on nuget.org

### ISSUE THREAD

**Issue by L3Z4** [elastic/apm-agent-dotnet#756]
The nupkg is produced by the CI  (https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/master/216/), and available [here](https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/master/216/artifact/apm-agent-dotnet/src/Elastic.Apm.SqlClient/bin/Release/Elastic.Apm.SqlClient.1.3.1.nupkg).

This not published yet on nuget.org.

**Comment by gregkalapos** [comment]
Hey @L3Z4,

this is intentional, we know about this. That package is not 100% ready yet. 

https://github.com/elastic/apm-agent-dotnet/issues/702 is about the documentation and there are some things we need to figure out for it before we officially release it.

Closing this now, since this is on our radar already.
