### ISSUE TITLE
ServerUrls: Uri expects protocol in front of the ip/domain + AbstractConfigurationReader does not log

### ISSUE THREAD

**Issue by mhensen** [elastic/apm-agent-dotnet#80]
No matter what I put in I always end up with a localhost:8200 as address.

{

  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  },
  "AllowedHosts": "*",
  "ElasticApm": {
    "LogLevel": "Debug",
    "ServerUrls": "172.26.xxx.xxx"
  }
}

based on the sample..

I would like to try this as my error logging from an asp.net api service

With kind regards,

Michael

**Comment by gregkalapos** [comment]
Thanks for opening this issue @mhensen! 

I looked into this and we have a couple of issues here for me to fix.

Let's start with your problem: if you put `http://` in front of the ip, it should work. 
E.g.:
` "ServerUrls":  "http://172.26.1.2"`

I think you should be good to go with this.

The problems I discovered:
- The `Logger` property in `AbstractConfigurationReader` remains null. If we can't parse the `ServerUrls` config setting into a `Uri` we log an error and default to `http://localhost:8200`. Unfortunately since the `Logger` was `null` this error message wasn't printed. So TODO nr. 1 for me: fix the logger.
-  We parse the `ServerUrls` setting into a `System.Uri`, which isn't happy if we don't put `http://` in front of the ip. This is not good, so TODO nr. 2: make sure we default to http or https.

TODO nr. 3: cover this with tests.

Sorry about this and thanks for trying the agent! Let me know in case the workaround did not help or if you have another issue. If you don't mind I'll change the description with my findings.

**Comment by mhensen** [comment]
Thanks for the quick response!

I'll give it a go later on..  
I saw there is an option of using Environment variables for config although I am not quite sure how this would be set.. I would like this option as we will be running this in a kubernetes environment.
Could you explain this option a bit more?

**Comment by gregkalapos** [comment]
Sure! 

In case of the service name you can just set the `ELASTIC_APM_SERVER_URLS` environment variable to your APM Server. 

E.g. on Windows to set it system-wide you can just execute:

`setx ELASTIC_APM_SERVER_URLS “http://172.26.1.2“`

On Linux:

`export ELASTIC_APM_SERVER_URLS=http://172.26.1.2`

Once you do this, all agents that see this environment variables will automatically pick up this setting.

There is one thing to add here: 
In the [sample application in this repo](https://github.com/elastic/apm-agent-dotnet/tree/master/sample/SampleAspNetCoreApp) the agent is registered by passing an `IConfiguration` to it:

> app.UseElasticApm(Configuration);

This means the agent will read config settings through from this `IConfiguration` instance. If you don’t want the agent to read configs from the `aspsettings.json` file and you are ok with reading settings only from environment variables, then the easiest is to just remove the `Configuration` parameter.  In this case the agent defaults to read settings only from environment variables.

If you want the agent to both read the `appsattings.json` file and the environment variables then make sure your `IConfiguration` is configured to read environment variables, like this:

In your `Program.cs` you do this:

public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>

```
WebHost.CreateDefaultBuilder(args)
   .ConfigureAppConfiguration( n=> n.AddEnvironmentVariables()) //This line adds env. vars to the config.
   .UseStartup<Startup>();
```

And then when you register the agent in `Startup.cs` you do this:

```
public class Startup
{
	public Startup(IConfiguration configuration) => Configuration = configuration;

	public IConfiguration Configuration { get; }


	public void Configure(IApplicationBuilder app, IHostingEnvironment env)
	{
		app.UseElasticApm(Configuration);
 		//…
	}
}
```

**Comment by gregkalapos** [comment]
@mhensen I pushed an improvement on this in #82.

I also realized that the [documentation](https://github.com/elastic/apm-agent-dotnet/blob/master/docs/configuration.asciidoc#serverurls) specifically says that you have to add the protocol to the server url (`http` or `https`), so we won't default to anything. Mainly because other agents don't do that either.

Nevertheless if this happens again you will see an error in the logs, and I also updated the sample app, because previously it had a value without `http` and that can be confusing.

Let me know if you have any other question on this, otherwise I'll close this issue.

Thx for trying out the agent!
