### ISSUE TITLE
Metrics reporting works, but not Transactions, on one single environment

### ISSUE THREAD

**Issue by ffMathy** [elastic/apm-agent-dotnet#824]
Here's a funny bug.

In my development environment, Elastic APM works just fine. It reports both transactions and metrics. However, when I deploy the same application to my production environment, ONLY metrics are reported.

What kind of condition can lead to this, and how can I fix it?

**Comment by gregkalapos** [comment]
Hi @ffMathy 

> What kind of condition can lead to this, and how can I fix it?

I'd need more info for this. 

2 things: 
- Can you share more about the application? Like, ASP.NET Core, or ASP.NET (classic), or something else? 
- Can you turn on agent logs (preferable on Debug level) and add the logs here?

**Comment by ffMathy** [comment]
It's an ASP .NET Core 3.1 application.

As for the logs, how do I turn it on?

**Comment by gregkalapos** [comment]
> It's an ASP .NET Core 3.1 application.
> 
> As for the logs, how do I turn it on?

Ok, for ASP.NET Core it's fairly easy - with that setup the agent integrates with the ASP.NET Core logging system, so you'll see the APM Agent logs in your normal logs (e.g. either on the console on a simple setup, or if you configured a logger like Serilog, then the agent logs will end up in your sink as any other logs). 

If you pass an `IConfiguration` instance to the `UseAllElasticApm` or `UseElasticApm` method then you can configure the agent log level like [this](https://www.elastic.co/guide/en/apm/agent/dotnet/current/configuration-on-asp-net-core.html#sample-config).

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Elastic.Apm": "Debug"
    }
  }
// .... more configs
}
```

If you don't pass an `IConfiguration` instance just set the environment variable `ELASTIC_APM_LOG_LEVEL` to `Debug`.

**Comment by ffMathy** [comment]
Alright, I have logs now. What part of the logs do you want? I can see that some of them include sensitive data, and there's a lot of them.

Do you want the first logs right after startup, or perhaps from a specific log level?

**Comment by gregkalapos** [comment]
> Alright, I have logs now. What part of the logs do you want? I can see that some of them include sensitive data, and there's a lot of them.
> 
> Do you want the first logs right after startup, or perhaps from a specific log level?

It'd be good to have logs from the point when a web request comes in. Maybe logs from [this file](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/ApmMiddleware.cs) or from [this file](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Model/Transaction.cs). 

In terms of log level: if there is an error or warning then it'll already probably tell the reason, if not we need to look at debug logs - if that does not help either we can move to trace logs (that'll be a lot potentially, so I'd leave it as the last step).

**Comment by ffMathy** [comment]
I have left out the log statements that contain URLs (the ones saying "sending <whatever> to the server"), as they are sensitive.

**Comment by ffMathy** [comment]
![image](https://user-images.githubusercontent.com/2824010/79559868-c36f5000-80a6-11ea-8e3a-432e04352d14.png)
![image](https://user-images.githubusercontent.com/2824010/79559939-e0a41e80-80a6-11ea-90b9-c2ba56a0e1f3.png)

**Comment by ffMathy** [comment]
Those are the first minute or so of activity.

My code in the startup is as follows:
```
app.UseElasticApm(_configuration);
Agent.Tracer.StartTransaction("Ping", "request").End();
```

So I would expect that transaction to appear.

**Comment by gregkalapos** [comment]
> Those are the first minute or so of activity. 

I looked at it, unfortunately I don't see anything suspicious other than the fact that nothing happens for incoming requests - no sign of that. 

 > My code in the startup is as follows:
> So I would expect that transaction to appear.

That's a good point, yes it should appear. 

Can you turn on `Trace` log level? In the transaction creation we mostly log on trace level. My idea is to generate the same log with trace and see what happens with that transaction.

**Comment by ffMathy** [comment]
I think `Trace` was already turned on there? What leads you to think it wasn't?

**Comment by gregkalapos** [comment]
>  What leads you to think it wasn't?

Since there is `Agent.Tracer.StartTransaction("Ping", "request").End();` in your code, I expected to see [this](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Model/Transaction.cs#L116) trace log. 

But, now that you updated your comment I think the issue is just that I don't see relevant part of the logs. [Here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Api/Tracer.cs#L54) the agent also prints a log on debug level - I don't see that either. 

The approach would be to follow that transaction because as you state it does not get to the APM Server - I need logs to follow that transaction.

**Comment by gregkalapos** [comment]
Ok, great to know you found the root cause. 

When the agent is already initialized then the next try to initialize an already initialized agent throws an exception [here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Agent.cs#L198) - in this scenario if `StartTransaction` initialized the agent then `UseElasticApm` should throws that exception - I wonder if you got that exception but maybe it did not became visible from some other reason.

The problem you have is known - there is the `Elastic.Apm.Agent.IsConfigured` property - just check that in the code where you potentially start the transaction before `UseElasticApm` is executed - with that if `UseElasticApm` was not executed, nothing happens, otherwise the transaction will be created. I'll add this to our doc.

> It should just be a no-op instead, if the agent is not ready yet, with a log statement.

That is a very valid option, the reason we did not go with that is that: 1) that way you'll always need to initialize the agent explicitly, which in some cases is not needed 2) people may miss the log, and the opposite happens - they wonder why the transaction is not created. So we went with implicitly initalizing the agent and then report double initialization with an exception if that happens.

**Comment by ffMathy** [comment]
I have a try-catch around that error, because of the static sickness. 

I have to have that try-catch, because or else my integration tests will fail (because they initialize the startup method multiple times for obvious reasons). That was the reason I didn't discover it.

Which brings me to: Why were statics chosen originally? It introduces global state which becomes a pain to test. Why not register the APM Agent in the IOC container as a Singleton?

> That is a very valid option, the reason we did not go with that is that: 1) that way you'll always need to initialize the agent explicitly, which in some cases is not needed 2) people may miss the log, and the opposite happens - they wonder why the transaction is not created. So we went with implicitly initalizing the agent and then report double initialization with an exception if that happens.

I have a suggestion to improve that further. Why not make it a no-op that then just logs that nothing was sent, because no configuration was made? Think about it - right now you have not really solved the problem, because you actually allow implicit agent initializations _with the wrong configuration_, which will actually lead to the exact same issue you were trying to solve with it (transactions not showing up).

Also I personally think people should always explicitly initialize something if they want to use it. The other just feels highly magical - I like to be in control of my software. With this, it feels like it has a life on its own, if you know what I mean?

I realize it may sound a bit negative all of the above - that is not at all the intention. I'm just in disagreement with some of the decisions made here, and I truly think I can help suggesting how it can be better. I'm super grateful for your quick responses and the way you deal with the issue at hand.

**Comment by gregkalapos** [comment]
> Why not register the APM Agent in the IOC container as a Singleton?

Yes - for ASP.NET Core that is a goal we have - there is this issue about it: https://github.com/elastic/apm-agent-dotnet/issues/441 

> Which brings me to: Why were statics chosen originally?

Main reason is that we have a 1 process - 1 agent approach. If we would not force it to be a single instance then the whole payload sender could be instantiated multiple times which leads to questions like - is it then the same agent? How do we prevent that things are captured per agent instance? Do we re-run the service detection for the second instance, what about the thread that sends the data, do we have 1 per agent? What about fetching remote configs, how do we pass it to all instances? We also collect metrics - with this we need to prevent that we collect those multiple times. Furthermore by supporting `net461` we can't really rely on a DI system, because there may not be a DI system there. So allowing multiple agent instances would open up lots of issues.

Having said that #441 is definitely an important one and I totally hear your (and others') feedback on this.

> I have a suggestion to improve that further. Why not make it a no-op that then just logs that nothing was sent, because no configuration was made? Think about it - right now you have not really solved the problem, because you actually allow implicit agent initializations with the wrong configuration, which will actually lead to the exact same issue you were trying to solve with it (transactions not showing up).

Well, I don't 100% agree that it led to the exact same issue - what really happened is that we threw an exception clearly stating the problem - it was just caught and ignored. And I'd argue that we can't expect people to always check the logs (e.g. in IIS for ASP.NET classic apps it's not so easy to collect agent logs as it is in ASP.NET Core), on the other hand in order to not see the exception you have to actively write code to catch it.

But, yeah - not having implicit initialization could be an option, but we'd only do such a change in a major version update, so we don't break existing users.

So, I guess the 2 issues are independent:

- Have a better setup story for ASP.NET Core - totally agree with this one - #441 is about that and we want to do something here 
- Force explicit initialization. This is not sure we'd do, but overall I feel this isn't really a super big problem.

Also thanks for the nice words.

**Comment by ffMathy** [comment]
I agree with the above.

But my issue is still not solved. I don't know *which* call in my application gets made before the `UseElasticApm` call. Do you have any idea of how I can figure it out?

That's another dilemma with this approach.

**Comment by gregkalapos** [comment]
Oh... i see.

It must be something which runs before your `Configure` method. Can you maybe check in the agent logs what is the 1. transaction that is created? on Trace level you see this - based on it's name you can maybe figure out where you create that one.

Don't wanna make promises here, but I'm working on something which would enables us to initialize the agent outside the `Configure` method. Only reason we need to do it there right now is that we register a middleware, so we need the `IApplicationBuilder`, but actually we could maybe (again, this is not final) get rid of the middleware and then you can initialize the agent earlier in the process potentially - that way you could make sure you initialize the agent very early in the app in such cases.

**Comment by ffMathy** [comment]
Ah that's a good idea. I'll analyze the logs and get back.

And that other idea is good too! I already do it in my NuGet package here: https://github.com/ffMathy/FluffySpoon.AspNet.NGrok

**Comment by gregkalapos** [comment]
@ffMathy did you manage to resolve this?

**Comment by gregkalapos** [comment]
Feel free to reopen if further discussion is needed.

**Comment by sabiland** [comment]
> Ok, great to know you found the root cause.
> 
> When the agent is already initialized then the next try to initialize an already initialized agent throws an exception [here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Agent.cs#L198) - in this scenario if `StartTransaction` initialized the agent then `UseElasticApm` should throws that exception - I wonder if you got that exception but maybe it did not became visible from some other reason.
> 
> The problem you have is known - there is the `Elastic.Apm.Agent.IsConfigured` property - just check that in the code where you potentially start the transaction before `UseElasticApm` is executed - with that if `UseElasticApm` was not executed, nothing happens, otherwise the transaction will be created. I'll add this to our doc.
> 
> > It should just be a no-op instead, if the agent is not ready yet, with a log statement.
> 
> That is a very valid option, the reason we did not go with that is that: 1) that way you'll always need to initialize the agent explicitly, which in some cases is not needed 2) people may miss the log, and the opposite happens - they wonder why the transaction is not created. So we went with implicitly initalizing the agent and then report double initialization with an exception if that happens.

Man, that was hard to debug & find that this was also the issue in my case.
