### ISSUE TITLE
Example of configuring agent in .NET Core console app

### ISSUE THREAD

**Issue by TailyFair** [elastic/apm-agent-dotnet#829]
**Is your feature request related to a problem? Please describe.**
It's not clear how to configure standard .NET Core app (Not ASP.NET Core). In current `HttpListenerSample` sample Agent is not configured and uses defaults. It's confusing how to setup Agent if I want to change `ServerUrls`.

**Describe the solution you'd like**
I would like to see some example on how to configure Agent in simple .NET Core console app.

Or make Agent simpler to configure, to allow just pass `IConfiguration` or set configure with builder pattern.

**Comment by gregkalapos** [comment]
Hi @TailyFair,

I opened #831 to add some more docs on this.

But this is already covered [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/configuration.html) and should be simple - you can just use environment variables to configure the agent. In order to [set `ServerUrls` you can](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-reporter.html#config-server-urls) just set the environment variable `ELASTIC_APM_SERVER_URLS`

>  to allow just pass `IConfiguration` 

We also support `net461`, and `IConfiguration` does not exist there, so that's unfortunately not an option.

**Comment by TailyFair** [comment]
Thank you for your response @gregkalapos. Changes to documentation in PR I believe are sufficient.

Environmental variables are partial solution to my use case, since there are multiple apps running in singe VM, so while `ServerUrls` is shared between all apps, settings like `ServiceName`, `ServiceVersion` and `Environment` are different per app.

I ended up implementing `IConfigurationReader` and `IApmLogger` on my own to have full control of configuration without environmental variables usage.

After PR is merged, I think this can be closed.

**Comment by gregkalapos** [comment]
Thanks for the feedback @TailyFair.

Implementing `IConfigurationReader` is also a totally valid option - maybe 1 thing to consider: you can also set the environment variable in C# with `Environment.SetEnvironmentVariable`. If you do that before the agent initializes maybe you can set the few settings that way instead of implementing the whole `IConfigurationReader` interface. I saw some people doing this, so I though I share this.

**Comment by TailyFair** [comment]
Great idea, will try that out! Thanks for documentation improvement.
