### ISSUE TITLE
.net Below version4.6.1 can not sent data？？

### ISSUE THREAD

**Issue by vicentwu** [elastic/apm-agent-dotnet#833]
**Describe the bug**
my application use .net4.0 or 4.5 version
When I finished the corresponding configuration, the agent status is wrong and no data is sent
For the lower version, how can I implement the function？

**To Reproduce**
1. Use this config '...'
2. Then call '....'
3. Then do '....'
4. See error：have no data from agent

**Expected behavior**
Is it possible to support versions below 4.6.1 in the future

**Comment by gregkalapos** [comment]
Hi @vicentwu 

The latest version we support is 4.6.1 - that is what we also communicate [in our docs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/supported-technologies.html#supported-dotnet-flavors). 

So this is expected behaviour, the agent currently does not support .NET Framework 4.0 or 4.5. 

The main reason is that those versions are EOL and sharing code between let's say .NET Framework 4.0 and .NET Core 3.0 would be very hard. Short term we don't have any plan to support those versions.
