### ISSUE TITLE
Memory Leak in ProcessingRequests in ASP.Net

### ISSUE THREAD

**Issue by cbo100** [elastic/apm-agent-dotnet#867]
**Describe the bug**
Starting in 1.5, "ProcessingRequests" never has removal called for a majority of HTTP Requests.

Leads to an unbounded memory leak. Also means the spans are never ended, so the HTTP Calls aren't included in APM (See #863 )

Observation (which I'm still trying to trace the exact split of working/non-working addresses):
- localhost/private requests affected
- public internet requests not affected

The "System.Net.Http.Desktop.HttpRequestOut.Stop" event stops being generated for requests that aren't to the public internet.

~And a doubled up "System.Net.Http.Desktop.HttpRequestOut.Start" event starts being generated for requests that are going to public internet~ - caused by redirect

**To Reproduce**
1. Create basic ASP.Net WebAPI project with APM 1.5.1
2. Use HttpClient to GET a URL repeatedly
3. Observe no HTTP spans logged
4. Observe memory leak

**Expected behavior**
All HTTP Spans logged, no memory leak.

Example controller action that will generate the problem:

```
       public async Task<string> Get(int id)
        {
            var url = "http://www.elastic.co";
            switch (id)
            { 
                case 1:
                    url = $"http://{ControllerContext.Request.RequestUri.Host}:{ControllerContext.Request.RequestUri.Port}/api/testing";
                    break;
                case 2:
                    url = "http://localhost:49487/api/values";
                    break;
                case 3:
                    url = "http://127.0.0.1:49487/api/values";
                    break;
            }

            using (var httpClient = new HttpClient())
            {
                
                var response = await httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Get, url));
                var content = await response.Content.ReadAsStringAsync();
                return $"Downloaded {content.Length} from {url}";
            }
        }
```

**Comment by cbo100** [comment]
Here's a reproduction of the issue:

https://github.com/cbo100/apm-bug-repro/commits/master

A "file new" .Net Framework Web API project.

Manually added the implementations of Diag listeners in the base case to see that the start/stop are all generated.

Then adding 1.4.0, then adding 1.5.0, showing the problem.

Seems any host on the private subnet will not log a stop event. 

The double start event is HTTPS redirect I'm guessing.

**Comment by cbo100** [comment]
![image](https://user-images.githubusercontent.com/122772/83325279-7a6a0880-a2ae-11ea-8f6c-a8f0abdd8511.png)

Screenshot from dotMemory showing the ProcessingRequests collection

**Comment by cbo100** [comment]
Worked out the reason only certain addresses getting a stop event - it's the redirect gets a stop. 

Any request thats direct, no stop event.

**Comment by gregkalapos** [comment]
Thanks for the info @cbo100. 

@SergeyKleyman could you take a look at this one?

**Comment by SergeyKleyman** [comment]
> Starting in 1.5, "ProcessingRequests"

@cbo100 Do you mean that for the same scenario version 1.5 of the agent does have memory leak but for some version before 1.5 doesn't?

**Comment by cbo100** [comment]
@SergeyKleyman I apologise that my test case was bloated with my other test code, I have a more accurate way to reproduce this with less junk from my test:

Visual Studio 2019 16.6

1. "File New - 'Asp.Net Web Application (.Net Framework)'"
2. Add a HttpClient usage to one of the controllers
3. Install and configure Elastic.Apm 1.4.0

- Observe: The request spans are logged, but not HttpClient request child spans.

4. Use NuGet to upgrade System.Diagnostics.DiagnosticSource from 4.0.0 to 4.6.0

- Observe: The request spans AND the HttpClient child request spans are both logged. No memory leak.

So upgrading that package is what enables the HttpClient spans in 1.4.0 to work.

5. Use NuGet to upgrade Elastic.Apm.AspNetFullFramework from 1.4.0 to 1.5.1

- Observe: The request spans are logged, but not the HttpClient child spans. Also, the memory leak is present.

**Comment by SergeyKleyman** [comment]
>I apologise

@cbo100
No apology necessary - we are very glad to see community using the agent and engaging with us in making it better for everybody. Thank you very much for putting so much effort and providing the results of very detailed investigation - I'm sure it will help us resolve the issue much more quickly.

**Comment by sluebbert** [comment]
I haven't done the effort to narrow down a root cause to ensure it is the same, but I can confirm that we have the same side effects and that we had to downgrade to version 1.4 as well to avoid a memory leak. Auto HttpClient spans also start working again when downgrading back to 1.4. We saw about a 1gb growth in memory per about 12 hours of use. Eventually we have to restart the services to restore function.

In our situation, we saw the issue within a .net framework windows service where we "faked" the `HttpApplication`. What I mean here is that we have code in the OnStart method of the service that looks like this:
`module.Init(new HttpApplication());`
where module is an instance of `ElasticApmModule`. I think we did that to force the configuration from the web config to load up since this service doesn't listen for incoming http calls.
This windows service listens to events from a subscription. All transactions are manually created from the event listener hooks. The memory leak seems to impact these services more harshly when they have more user defined spans.

Thanks,

**Comment by rorueda** [comment]
I've done some investigation on this issue and here is what I have found out. 

In #800, the agent started creating an `Activity` with the  `W3C` format for each transaction. Because of this, the children activities, that are created for the http requests, are created with the same format. And then we have the `HttpHandlerDiagnosticListener` issues when using `W3C`: https://github.com/dotnet/corefx/pull/40777 and https://github.com/dotnet/runtime/issues/38152. This seems to explain why this issue is present only in 1.5.0 and 1.5.1.

It was particularly difficult to understand why the AspNetFullFrameworkSampleApp seemed to work (using home/Contact). It turned out there are two other modules being used there: `TelemetryCorrelationHttpModule` and `ApplicationInsightsWebTracking`. Didn't have the time to investigate exactly what was going on, but, by removing both, the issue was reproduced.

A possible workaround is to force the `Hierarchical` format on children activities by setting `Activity.ForceDefaultIdFormat` to `true` (might want to make sure `Hierarchical` is the default - the modules above, for instance, were setting it to `W3C`) , but I'm not sure this is not going to break things. 

As for the memory leak problem, it's a bit odd that spans of and ended transaction are kept in memory. I don't know the internals, but they probably should be dropped (maybe with some kind of warning). I think it could be a good safeguard for leaks like this.

Any thoughts?

**Comment by gregkalapos** [comment]
Thanks @rorueda - super useful comment.

> In #800, the agent started creating an Activity with the W3C format for each transaction. Because of this, the children activities, that are created for the http requests, are created with the same format. And then we have the HttpHandlerDiagnosticListener issues when using W3C: dotnet/corefx#40777 and dotnet/runtime#38152. This seems to explain why this issue is present only in 1.5.0 and 1.5.1.

Yes, nothing to add here, very good analysis. Thank you! 

> It was particularly difficult to understand why the AspNetFullFrameworkSampleApp seemed to work (using home/Contact). It turned out there are two other modules being used there: TelemetryCorrelationHttpModule and ApplicationInsightsWebTracking. Didn't have the time to investigate exactly what was going on, but, by removing both, the issue was reproduced.

Those were probably there, because they are part of the standard template (or.. well... the checkbox was active to add AI...). I removed those - it was not intentionally there.

> A possible workaround is to force the Hierarchical format on children activities by setting Activity.ForceDefaultIdFormat to true (might want to make sure Hierarchical is the default - the modules above, for instance, were setting it to W3C) , but I'm not sure this is not going to break things.

That is definitely an option and I suspect Application Insights also does it this way, but to me this sounds very intrusive. I opened #896 and the idea is that I made the feature to keep ids on `Activity` in-sync with Elastic APM optional and for ASP.NET Classic I turned it off. If we'd do `Activity.ForceDefaultIdFormat = true` with hierarchical id, then this feature would not work anyway - Elastic APM is W3C-only and we ignore hierarchical ids. Long term I'll see if we can update to a newer DiagnosticSource version.

**Comment by gregkalapos** [comment]
#896 merged, with that we have the same behavior for ASP.NET Classic as we had with pre `1.5.0` versions.
