### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by ejsmith** [elastic/apm-agent-dotnet#874]
I need to have Redis commands captured in the APM data. I saw somewhere that it is planned, but not currently available. Is this something you would be interested in taking a PR for? If so, do you have any current thoughts on how this would be implemented or any other information you can point me in the right direction on?

**Comment by ejsmith** [comment]
Here are some resources I found:

https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.StackExchangeRedis

https://github.com/elastic/apm-agent-java/pull/949/files

**Comment by kleintech** [comment]
We are also using StackExchange's Redis lib and are seeking a path forward here. Instead of custom-instrumenting our own Spans, I'd love for our team to be able to contribute here.

The [Adding support for instrumenting new libraries/frameworks/APIs](https://github.com/elastic/apm-agent-dotnet/blob/master/CONTRIBUTING.md#adding-support-for-instrumenting-new-librariesframeworksapis) section in the Contributing docs are currently pending. What is the recommended path forward for implementing new instrumentation at the agent level like this? Is it just a matter of forking the OpenTelemetry implementation over into the Elastic APM agent?

**Comment by kleintech** [comment]
Also - Thoughts on being more-specific here on the type of Redis support we're discussing by renaming this issue to something like ".NET Core support for StackExchange.Redis"?

**Comment by gregkalapos** [comment]
@kleintech I haven't looked into this in more details, but regarding

> What is the recommended path forward for implementing new instrumentation at the agent level like this? 

Just look at one of our existing auto instrumentation - I think that's the best way to get an idea on how it should work. For example the [EF Core](https://github.com/elastic/apm-agent-dotnet/tree/master/src/Elastic.Apm.EntityFrameworkCore) one is probably a good start - that's fairly easy to understand.

So similarly to that, it would be basically just creating spans and filling the context. The OpenTelemetry implementation can be a good source on how to get notified about redis internals (haven't looked at the details there, but definitely worth checking out).

If you already have something, feel free to submit a PR - I'm happy to look at it.

> Thoughts on being more-specific here on the type of Redis support we're discussing by renaming this issue to something like ".NET Core support for StackExchange.Redis"

If we start working on StackExchange.Redis we can rename this. So far we don't have a clear strategy on which redis library to support - if we get a PR specifically for StackExchange.Redis, then I'd say we can rename. Otherwise let's keep it general for now until we have more specific plans.

**Comment by russcam** [comment]
I've opened #1063 to support capturing redis commands with StackExchange.Redis
