### ISSUE TITLE
Design approach inquiry - heavy use of internal scopes

### ISSUE THREAD

**Issue by WhitWaldo** [elastic/apm-agent-dotnet#921]
Good evening - I forked your repo with the intent of building another package that was more compatible with other dependency injection providers for non-ASP.NET Core services running atop Microsoft's Service Fabric. While looking at how each of your packages work, I started to dive into the skeleton of an implementation myself and quickly ran into your scoping approach in Elastic.Apm. 

Just about your entire core library is scoped as internal and explicitly made available to your other packages via [assembly:InternalsVisibleTo] [attributes](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Agent.cs). 

Short of submitting a pull request atop an existing package, I don't know how I can possibly contribute any other agents back to your repo. I don't have your signing certificate and if I modify your core library to a flip everything to public, you'll likely reject any pull requests back on that alone.

I'm curious - why did you go with this route and is there any path forward I might take to build a more compatible agent for my own scenario?

**Comment by gregkalapos** [comment]
We would like to make more things public in the future - the main idea of having things internal is to have less breaking changes.

Overall when you instrument a library, you'd typically start a transaction and spans and set properties on those. These are already public. 

Happy to look into other things that could cause issues.

Can you share specifics about your issues? What internal classes would you need to be public?

**Comment by WhitWaldo** [comment]
I wasn't looking so much to instrument a library so much as create similar orchestration engine support as you already have for Kubernetes. My application runs atop Microsoft's Service Fabric and largely uses .NET console-like projects. However, because of the Service Fabric dependency, they do not yet support the use of IGenericHost and thus are a bit resistant to your approach for agent registration.

I was looking at doing a couple of things as part of my POC that was ultimately blocked in because of your use of internals:

1) Support Service Fabric Remoting (not .NET remoting, but a built-in feature of that framework) to automatically inject and read span IDs out from inter-service calls.
2) Automatically tag service calls with service-specific information (e.g. node type, partition IDs, etc.)
3) Service Fabric Actor instrumentation
4) Configure via the per-service settings store available to Service Fabric services

This has been entirely blocked because of your heavy use of internal scoping. The use of registration via the IGenericHost is great for anyone using a recent version of ASP.NET Core, but unfortunately, we're both not using ASP.NET Core (for most of our services) and blocked from using IGenericHost on all services (due to lack of Service Fabric support in the current release). Thus, I was first looking to expose the various DI registrations you're performing so I might utilize a different DI container (Autofac), but you've got all the interfaces and their concrete implementations hiding behind internals.

Ideally, you'd refactor this in a couple of ways:
- Flip nearly all but truly internal interfaces as public in the core library (offhand, this would be all but /BackendComm, /Helpers, and /Logging) so everything can be utilized in a DI registration
- Migrate all the concrete implementations out to the services that actually need them (e.g. HttpDiagnostics listeners out to the .AspNetCore project, perhaps move DbSpanCommon out to a per-DB common implementation, etc.)
- Allow for a bring-your-own-DI-container approach - offer the IHostBuilder methods, but don't visibility-lock those as being the only acceptable registration methods
- Allow for a bring-your-own-configuration approach. You've already got IConfigurationReader public, but if I can't create an instance of your ApmAgent class or specify it in your ApmAgent factory, it's of little use.

As such, I don't really see any path forward to contribute meaningfully to this project to utilize Elastic's APM to instrument our application.

**Comment by gregkalapos** [comment]
I see, interesting use-case!

> However, because of the Service Fabric dependency, they do not yet support the use of IGenericHost and thus are a bit resistant to your approach for agent registration.

You don't need `IGenericHost` in order to start the agent. We also have a plain simple `Agent.Setup` method that you can call anywhere and that'll initialize the agent. Like this: `Agent.Setup(new AgentComponents());`. 

> Thus, I was first looking to expose the various DI registrations you're performing so I might utilize a different DI container (Autofac), but you've got all the interfaces and their concrete implementations hiding behind internals.

What would you like to inject through DI? Elastic APM is basically a tracing tool - you can inject the `ITracer`, like this:

```
Agent.Setup(new AgentComponents());

// Here we register the `ITracer` to Autofac - the `Agent.Tracer` always gives you the tracer.
var builder = new ContainerBuilder();
builder.RegisterInstance(Agent.Tracer)
	.As<ITracer>();
builder.RegisterType<MyClass>();
```

Now, to your specific point (there is a complete sample below - but I'd like to also give some response before I show the code)

> 1. Support Service Fabric Remoting (not .NET remoting, but a built-in feature of that framework) to automatically inject and read span IDs out from inter-service calls.

This to me really sound like you'd like to implement distributed tracing. I assume you mean inject and read trace IDs, right? A span itself has and id and that's typically generated when the span is started, you don't really want to inject or read that. [Here](https://www.elastic.co/guide/en/apm/get-started/current/distributed-tracing.html) is a good doc on this topic.

> 2. Automatically tag service calls with service-specific information (e.g. node type, partition IDs, etc.)

 We have a [`Labels` property](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-transaction-tags) on our transaction, you can put this type of information there. Once you have a tracer, you can just call `tracer.CurrentTransaction.Labels["MyCustomInfo"] = "foo";` and decorate the transaction with this information. You'll get the tracer through DI (as I show it in the code sample) or by simply using `Agent.Tracer`.

> 3. Allow for a bring-your-own-DI-container approach - offer the IHostBuilder methods, but don't visibility-lock those as being the only acceptable registration methods

This is shown on the sample code. We don't really want to overcomplicate this. From my understanding an `ITracer` is the only one which would make sense to inject in case of a tracing system. Maybe another one for metrics, for that we have an open issue. What else would you like to inject? Happy to to take specific feedback on this, but in that case I really need to understand what you'd like to inject. Turning on the agent and adding part of the agent into a DI container isn't the same, these should be handled separately. In case of `IHostBuilder` it's the same step, but that's only to make things easier for users.

> 4. Configure via the per-service settings store available to Service Fabric services

Ok, I hear you. We just merged a PR which adds the 4. way of configuring the agent (we support environment variables, `IConfiguration` on .NET Core, `web.config` or `app.config` on Full Framework, plus now a custom class implementing our `IConfigurationReader` on .NET Core), plus we have central config where you configure the agent in Kibana (this is in progress, limited number of configs are available yet, but will be continuously extended)

Also, you can always do this:

```
class MyCustomConfigReader : Elastic.Apm.Config.IConfigurationReader
{
	// Implement all the configs, you can also read those from some service fabric services
}

// and then when you initialize the agent:

Agent.Setup(new AgentComponents(configurationReader: new MyCustomConfigReader()));
```

So, here are some more code snippets that may help you:

```
// Setup the agent - this initializes the agent, it'll start collecting metrics and starts all the components, so you can
// start transactions, spans and those will be sent to APM server
Agent.Setup(new AgentComponents(configurationReader: new MyCustomConfigReader()));

// At any point you can turn on auto instrumentation, here we turn on auto instrumentation for outgoing HTTP calls
// So in case there is an active transaction, all HTTP calls through HttpClient will be captured
Agent.Subscribe(new HttpDiagnosticsSubscriber());

// Here we turn on Elasticsearch instrumentation - all calls to elasticsearch will be captured when there is an active transaction
Agent.Subscribe(new ElasticsearchDiagnosticsSubscriber());

// Here we register the `ITracer` to Autofac - the `Agent.Tracer` always gives you the tracer.
var builder = new ContainerBuilder();
builder.RegisterInstance(Agent.Tracer)
	.As<ITracer>();

var container = builder.Build();

// Let's say this is our 1. service
await using (var scope1 = container)
{
	// Now let's use the tracer
	var tracer = scope1.Resolve<ITracer>();
	
        // Start a basic transaction
	var transaction = tracer.StartTransaction("MyTransaction", "ServiceFabricCall");
	
	try
	{
		// Run your apps code - note that this does not have to be a single method; you can have the `tracer.StartTransaction` part at any point, then k
		// to the transaction and call .End() on it at any other point when the transaction is done.
		
		// Tag the transaction with custom information (note: you only need the tracer)
		tracer.CurrentTransaction.Labels["MyCustomInfo"] = "foo";
		
		// Serialize the trace to a string (in case this service calls the other service through HTTP, it'll be automatically serialized in an HTTP head
		var serializedTrace = tracer.CurrentTransaction.OutgoingDistributedTracingData.SerializeToString();
		// So, in case it's non-HTTP, transfer serializedTrace to the callee service
	}
	catch(Exception e)
	{
		transaction.CaptureException(e);
		throw;
	}
	finally
	{
		// finish transaction
		transaction.End();
	}
}


// Now let's say we are in the callee service (like a completely separate process)
await using (var scope2 = container)
{
	var tracer = scope2.Resolve<ITracer>();
	var distributedTracingData = GetSerializedTrace(); // Here we read the distributed tracing data
	var transaction2 = tracer.StartTransaction("MyService", "ServiceFabricCall",
		DistributedTracingData.TryDeserializeFromString(distributedTracingData));
	
	try
	{
		// app's code
	}
	finally
	{
		transaction2.End();
	}
}
```

**Comment by gregkalapos** [comment]
Closing now - I think there is no clear action plan at this point here.

Feel free to reopen if there are other questions related to this issue still open.
